//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim.sms;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfSourceGroupMemberInfo {

    private final static com.vmware.vim.sms.SourceGroupMemberInfo[] NULL_SOURCE_GROUP_MEMBER_INFO_ARRAY = new com.vmware.vim.sms.SourceGroupMemberInfo[ 0 ] ;
    public com.vmware.vim.sms.SourceGroupMemberInfo[] SourceGroupMemberInfo;

    public com.vmware.vim.sms.SourceGroupMemberInfo[] getSourceGroupMemberInfo() {
        if ((SourceGroupMemberInfo) == null) {
            return (NULL_SOURCE_GROUP_MEMBER_INFO_ARRAY);
        }
        return SourceGroupMemberInfo;
    }

    public void setSourceGroupMemberInfo(com.vmware.vim.sms.SourceGroupMemberInfo[] SourceGroupMemberInfo) {
        this.SourceGroupMemberInfo = SourceGroupMemberInfo;
    }

}
