//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim.sms;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfBackingStoragePool {

    private final static com.vmware.vim.sms.BackingStoragePool[] NULL_BACKING_STORAGE_POOL_ARRAY = new com.vmware.vim.sms.BackingStoragePool[ 0 ] ;
    public com.vmware.vim.sms.BackingStoragePool[] BackingStoragePool;

    public com.vmware.vim.sms.BackingStoragePool[] getBackingStoragePool() {
        if ((BackingStoragePool) == null) {
            return (NULL_BACKING_STORAGE_POOL_ARRAY);
        }
        return BackingStoragePool;
    }

    public void setBackingStoragePool(com.vmware.vim.sms.BackingStoragePool[] BackingStoragePool) {
        this.BackingStoragePool = BackingStoragePool;
    }

}
