//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim.sms;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPointInTimeReplicaInfo {

    private final static com.vmware.vim.sms.PointInTimeReplicaInfo[] NULL_POINT_IN_TIME_REPLICA_INFO_ARRAY = new com.vmware.vim.sms.PointInTimeReplicaInfo[ 0 ] ;
    public com.vmware.vim.sms.PointInTimeReplicaInfo[] PointInTimeReplicaInfo;

    public com.vmware.vim.sms.PointInTimeReplicaInfo[] getPointInTimeReplicaInfo() {
        if ((PointInTimeReplicaInfo) == null) {
            return (NULL_POINT_IN_TIME_REPLICA_INFO_ARRAY);
        }
        return PointInTimeReplicaInfo;
    }

    public void setPointInTimeReplicaInfo(com.vmware.vim.sms.PointInTimeReplicaInfo[] PointInTimeReplicaInfo) {
        this.PointInTimeReplicaInfo = PointInTimeReplicaInfo;
    }

}
