//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim.sms;

import java.util.Calendar;


/**
 * 
 */
@SuppressWarnings("all")
public class FailoverSuccessResult
    extends GroupOperationResult
{

    public String newState;
    public PointInTimeReplicaId pitId;
    public PointInTimeReplicaId pitIdBeforeFailover;
    private final static RecoveredDevice[] NULL_RECOVERED_DEVICE_INFO_ARRAY = new RecoveredDevice[ 0 ] ;
    public RecoveredDevice[] recoveredDeviceInfo;
    public Calendar timeStamp;

    public String getNewState() {
        return newState;
    }

    public void setNewState(String newState) {
        this.newState = newState;
    }

    public PointInTimeReplicaId getPitId() {
        return pitId;
    }

    public void setPitId(PointInTimeReplicaId pitId) {
        this.pitId = pitId;
    }

    public PointInTimeReplicaId getPitIdBeforeFailover() {
        return pitIdBeforeFailover;
    }

    public void setPitIdBeforeFailover(PointInTimeReplicaId pitIdBeforeFailover) {
        this.pitIdBeforeFailover = pitIdBeforeFailover;
    }

    public RecoveredDevice[] getRecoveredDeviceInfo() {
        if ((recoveredDeviceInfo) == null) {
            return (NULL_RECOVERED_DEVICE_INFO_ARRAY);
        }
        return recoveredDeviceInfo;
    }

    public void setRecoveredDeviceInfo(RecoveredDevice[] recoveredDeviceInfo) {
        this.recoveredDeviceInfo = recoveredDeviceInfo;
    }

    public Calendar getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Calendar timeStamp) {
        this.timeStamp = timeStamp;
    }

}
