//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim.sms;

import com.vmware.vim25.MethodFault;


/**
 * 
 */
@SuppressWarnings("all")
public class InactiveProvider
    extends MethodFault
{

    private final static FaultDomainProviderMapping[] NULL_MAPPING_ARRAY = new FaultDomainProviderMapping[ 0 ] ;
    public FaultDomainProviderMapping[] mapping;

    public FaultDomainProviderMapping[] getMapping() {
        if ((mapping) == null) {
            return (NULL_MAPPING_ARRAY);
        }
        return mapping;
    }

    public void setMapping(FaultDomainProviderMapping[] mapping) {
        this.mapping = mapping;
    }

}
