//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class AlarmFilterSpec
    extends DynamicData
{

    private final static ManagedEntityStatus[] NULL_STATUS_ARRAY = new ManagedEntityStatus[ 0 ] ;
    public ManagedEntityStatus[] status;
    public String typeEntity;
    public String typeTrigger;

    public ManagedEntityStatus[] getStatus() {
        if ((status) == null) {
            return (NULL_STATUS_ARRAY);
        }
        return status;
    }

    public void setStatus(ManagedEntityStatus[] status) {
        this.status = status;
    }

    public String getTypeEntity() {
        return typeEntity;
    }

    public void setTypeEntity(String typeEntity) {
        this.typeEntity = typeEntity;
    }

    public String getTypeTrigger() {
        return typeTrigger;
    }

    public void setTypeTrigger(String typeTrigger) {
        this.typeTrigger = typeTrigger;
    }

}
