//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostLowLevelProvisioningManagerFileReserveSpec {

    private final static com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveSpec[] NULL_HOST_LOW_LEVEL_PROVISIONING_MANAGER_FILE_RESERVE_SPEC_ARRAY = new com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveSpec[ 0 ] ;
    public com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveSpec[] HostLowLevelProvisioningManagerFileReserveSpec;

    public com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveSpec[] getHostLowLevelProvisioningManagerFileReserveSpec() {
        if ((HostLowLevelProvisioningManagerFileReserveSpec) == null) {
            return (NULL_HOST_LOW_LEVEL_PROVISIONING_MANAGER_FILE_RESERVE_SPEC_ARRAY);
        }
        return HostLowLevelProvisioningManagerFileReserveSpec;
    }

    public void setHostLowLevelProvisioningManagerFileReserveSpec(com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveSpec[] HostLowLevelProvisioningManagerFileReserveSpec) {
        this.HostLowLevelProvisioningManagerFileReserveSpec = HostLowLevelProvisioningManagerFileReserveSpec;
    }

}
