//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVirtualMachineProfileDetailsDiskProfileDetails {

    private final static com.vmware.vim25.VirtualMachineProfileDetailsDiskProfileDetails[] NULL_VIRTUAL_MACHINE_PROFILE_DETAILS_DISK_PROFILE_DETAILS_ARRAY = new com.vmware.vim25.VirtualMachineProfileDetailsDiskProfileDetails[ 0 ] ;
    public com.vmware.vim25.VirtualMachineProfileDetailsDiskProfileDetails[] VirtualMachineProfileDetailsDiskProfileDetails;

    public com.vmware.vim25.VirtualMachineProfileDetailsDiskProfileDetails[] getVirtualMachineProfileDetailsDiskProfileDetails() {
        if ((VirtualMachineProfileDetailsDiskProfileDetails) == null) {
            return (NULL_VIRTUAL_MACHINE_PROFILE_DETAILS_DISK_PROFILE_DETAILS_ARRAY);
        }
        return VirtualMachineProfileDetailsDiskProfileDetails;
    }

    public void setVirtualMachineProfileDetailsDiskProfileDetails(com.vmware.vim25.VirtualMachineProfileDetailsDiskProfileDetails[] VirtualMachineProfileDetailsDiskProfileDetails) {
        this.VirtualMachineProfileDetailsDiskProfileDetails = VirtualMachineProfileDetailsDiskProfileDetails;
    }

}
