//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVirtualDeviceConfigSpec {

    private final static com.vmware.vim25.VirtualDeviceConfigSpec[] NULL_VIRTUAL_DEVICE_CONFIG_SPEC_ARRAY = new com.vmware.vim25.VirtualDeviceConfigSpec[ 0 ] ;
    public com.vmware.vim25.VirtualDeviceConfigSpec[] VirtualDeviceConfigSpec;

    public com.vmware.vim25.VirtualDeviceConfigSpec[] getVirtualDeviceConfigSpec() {
        if ((VirtualDeviceConfigSpec) == null) {
            return (NULL_VIRTUAL_DEVICE_CONFIG_SPEC_ARRAY);
        }
        return VirtualDeviceConfigSpec;
    }

    public void setVirtualDeviceConfigSpec(com.vmware.vim25.VirtualDeviceConfigSpec[] VirtualDeviceConfigSpec) {
        this.VirtualDeviceConfigSpec = VirtualDeviceConfigSpec;
    }

}
