//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostCpuPackage {

    private final static com.vmware.vim25.HostCpuPackage[] NULL_HOST_CPU_PACKAGE_ARRAY = new com.vmware.vim25.HostCpuPackage[ 0 ] ;
    public com.vmware.vim25.HostCpuPackage[] HostCpuPackage;

    public com.vmware.vim25.HostCpuPackage[] getHostCpuPackage() {
        if ((HostCpuPackage) == null) {
            return (NULL_HOST_CPU_PACKAGE_ARRAY);
        }
        return HostCpuPackage;
    }

    public void setHostCpuPackage(com.vmware.vim25.HostCpuPackage[] HostCpuPackage) {
        this.HostCpuPackage = HostCpuPackage;
    }

}
