//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostProxySwitch {

    private final static com.vmware.vim25.HostProxySwitch[] NULL_HOST_PROXY_SWITCH_ARRAY = new com.vmware.vim25.HostProxySwitch[ 0 ] ;
    public com.vmware.vim25.HostProxySwitch[] HostProxySwitch;

    public com.vmware.vim25.HostProxySwitch[] getHostProxySwitch() {
        if ((HostProxySwitch) == null) {
            return (NULL_HOST_PROXY_SWITCH_ARRAY);
        }
        return HostProxySwitch;
    }

    public void setHostProxySwitch(com.vmware.vim25.HostProxySwitch[] HostProxySwitch) {
        this.HostProxySwitch = HostProxySwitch;
    }

}
