//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfByte {

    private final static byte[] NULL__BYTE_ARRAY = new byte[ 0 ] ;
    public byte[] _byte;

    public byte[] get_byte() {
        if ((_byte) == null) {
            return (NULL__BYTE_ARRAY);
        }
        return _byte;
    }

    public void set_byte(byte[] _byte) {
        this._byte = _byte;
    }

}
