//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostMultipathStateInfoPath {

    private final static com.vmware.vim25.HostMultipathStateInfoPath[] NULL_HOST_MULTIPATH_STATE_INFO_PATH_ARRAY = new com.vmware.vim25.HostMultipathStateInfoPath[ 0 ] ;
    public com.vmware.vim25.HostMultipathStateInfoPath[] HostMultipathStateInfoPath;

    public com.vmware.vim25.HostMultipathStateInfoPath[] getHostMultipathStateInfoPath() {
        if ((HostMultipathStateInfoPath) == null) {
            return (NULL_HOST_MULTIPATH_STATE_INFO_PATH_ARRAY);
        }
        return HostMultipathStateInfoPath;
    }

    public void setHostMultipathStateInfoPath(com.vmware.vim25.HostMultipathStateInfoPath[] HostMultipathStateInfoPath) {
        this.HostMultipathStateInfoPath = HostMultipathStateInfoPath;
    }

}
