//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfDatastoreMountPathDatastorePair {

    private final static com.vmware.vim25.DatastoreMountPathDatastorePair[] NULL_DATASTORE_MOUNT_PATH_DATASTORE_PAIR_ARRAY = new com.vmware.vim25.DatastoreMountPathDatastorePair[ 0 ] ;
    public com.vmware.vim25.DatastoreMountPathDatastorePair[] DatastoreMountPathDatastorePair;

    public com.vmware.vim25.DatastoreMountPathDatastorePair[] getDatastoreMountPathDatastorePair() {
        if ((DatastoreMountPathDatastorePair) == null) {
            return (NULL_DATASTORE_MOUNT_PATH_DATASTORE_PAIR_ARRAY);
        }
        return DatastoreMountPathDatastorePair;
    }

    public void setDatastoreMountPathDatastorePair(com.vmware.vim25.DatastoreMountPathDatastorePair[] DatastoreMountPathDatastorePair) {
        this.DatastoreMountPathDatastorePair = DatastoreMountPathDatastorePair;
    }

}
