//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostIpRouteEntry {

    private final static com.vmware.vim25.HostIpRouteEntry[] NULL_HOST_IP_ROUTE_ENTRY_ARRAY = new com.vmware.vim25.HostIpRouteEntry[ 0 ] ;
    public com.vmware.vim25.HostIpRouteEntry[] HostIpRouteEntry;

    public com.vmware.vim25.HostIpRouteEntry[] getHostIpRouteEntry() {
        if ((HostIpRouteEntry) == null) {
            return (NULL_HOST_IP_ROUTE_ENTRY_ARRAY);
        }
        return HostIpRouteEntry;
    }

    public void setHostIpRouteEntry(com.vmware.vim25.HostIpRouteEntry[] HostIpRouteEntry) {
        this.HostIpRouteEntry = HostIpRouteEntry;
    }

}
