//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfClusterActionHistory {

    private final static com.vmware.vim25.ClusterActionHistory[] NULL_CLUSTER_ACTION_HISTORY_ARRAY = new com.vmware.vim25.ClusterActionHistory[ 0 ] ;
    public com.vmware.vim25.ClusterActionHistory[] ClusterActionHistory;

    public com.vmware.vim25.ClusterActionHistory[] getClusterActionHistory() {
        if ((ClusterActionHistory) == null) {
            return (NULL_CLUSTER_ACTION_HISTORY_ARRAY);
        }
        return ClusterActionHistory;
    }

    public void setClusterActionHistory(com.vmware.vim25.ClusterActionHistory[] ClusterActionHistory) {
        this.ClusterActionHistory = ClusterActionHistory;
    }

}
