//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfGuestFileInfo {

    private final static com.vmware.vim25.GuestFileInfo[] NULL_GUEST_FILE_INFO_ARRAY = new com.vmware.vim25.GuestFileInfo[ 0 ] ;
    public com.vmware.vim25.GuestFileInfo[] GuestFileInfo;

    public com.vmware.vim25.GuestFileInfo[] getGuestFileInfo() {
        if ((GuestFileInfo) == null) {
            return (NULL_GUEST_FILE_INFO_ARRAY);
        }
        return GuestFileInfo;
    }

    public void setGuestFileInfo(com.vmware.vim25.GuestFileInfo[] GuestFileInfo) {
        this.GuestFileInfo = GuestFileInfo;
    }

}
