//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostFeatureCapability {

    private final static com.vmware.vim25.HostFeatureCapability[] NULL_HOST_FEATURE_CAPABILITY_ARRAY = new com.vmware.vim25.HostFeatureCapability[ 0 ] ;
    public com.vmware.vim25.HostFeatureCapability[] HostFeatureCapability;

    public com.vmware.vim25.HostFeatureCapability[] getHostFeatureCapability() {
        if ((HostFeatureCapability) == null) {
            return (NULL_HOST_FEATURE_CAPABILITY_ARRAY);
        }
        return HostFeatureCapability;
    }

    public void setHostFeatureCapability(com.vmware.vim25.HostFeatureCapability[] HostFeatureCapability) {
        this.HostFeatureCapability = HostFeatureCapability;
    }

}
