//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPropertyFilterUpdate {

    private final static com.vmware.vim25.PropertyFilterUpdate[] NULL_PROPERTY_FILTER_UPDATE_ARRAY = new com.vmware.vim25.PropertyFilterUpdate[ 0 ] ;
    public com.vmware.vim25.PropertyFilterUpdate[] PropertyFilterUpdate;

    public com.vmware.vim25.PropertyFilterUpdate[] getPropertyFilterUpdate() {
        if ((PropertyFilterUpdate) == null) {
            return (NULL_PROPERTY_FILTER_UPDATE_ARRAY);
        }
        return PropertyFilterUpdate;
    }

    public void setPropertyFilterUpdate(com.vmware.vim25.PropertyFilterUpdate[] PropertyFilterUpdate) {
        this.PropertyFilterUpdate = PropertyFilterUpdate;
    }

}
