//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostIoFilterInfo {

    private final static com.vmware.vim25.HostIoFilterInfo[] NULL_HOST_IO_FILTER_INFO_ARRAY = new com.vmware.vim25.HostIoFilterInfo[ 0 ] ;
    public com.vmware.vim25.HostIoFilterInfo[] HostIoFilterInfo;

    public com.vmware.vim25.HostIoFilterInfo[] getHostIoFilterInfo() {
        if ((HostIoFilterInfo) == null) {
            return (NULL_HOST_IO_FILTER_INFO_ARRAY);
        }
        return HostIoFilterInfo;
    }

    public void setHostIoFilterInfo(com.vmware.vim25.HostIoFilterInfo[] HostIoFilterInfo) {
        this.HostIoFilterInfo = HostIoFilterInfo;
    }

}
