//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVMwareDvsLacpGroupConfig {

    private final static com.vmware.vim25.VMwareDvsLacpGroupConfig[] NULL_V_MWARE_DVS_LACP_GROUP_CONFIG_ARRAY = new com.vmware.vim25.VMwareDvsLacpGroupConfig[ 0 ] ;
    public com.vmware.vim25.VMwareDvsLacpGroupConfig[] VMwareDvsLacpGroupConfig;

    public com.vmware.vim25.VMwareDvsLacpGroupConfig[] getVMwareDvsLacpGroupConfig() {
        if ((VMwareDvsLacpGroupConfig) == null) {
            return (NULL_V_MWARE_DVS_LACP_GROUP_CONFIG_ARRAY);
        }
        return VMwareDvsLacpGroupConfig;
    }

    public void setVMwareDvsLacpGroupConfig(com.vmware.vim25.VMwareDvsLacpGroupConfig[] VMwareDvsLacpGroupConfig) {
        this.VMwareDvsLacpGroupConfig = VMwareDvsLacpGroupConfig;
    }

}
