//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfClusterDasVmConfigInfo {

    private final static com.vmware.vim25.ClusterDasVmConfigInfo[] NULL_CLUSTER_DAS_VM_CONFIG_INFO_ARRAY = new com.vmware.vim25.ClusterDasVmConfigInfo[ 0 ] ;
    public com.vmware.vim25.ClusterDasVmConfigInfo[] ClusterDasVmConfigInfo;

    public com.vmware.vim25.ClusterDasVmConfigInfo[] getClusterDasVmConfigInfo() {
        if ((ClusterDasVmConfigInfo) == null) {
            return (NULL_CLUSTER_DAS_VM_CONFIG_INFO_ARRAY);
        }
        return ClusterDasVmConfigInfo;
    }

    public void setClusterDasVmConfigInfo(com.vmware.vim25.ClusterDasVmConfigInfo[] ClusterDasVmConfigInfo) {
        this.ClusterDasVmConfigInfo = ClusterDasVmConfigInfo;
    }

}
