//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVsanHostDiskMapInfo {

    private final static com.vmware.vim25.VsanHostDiskMapInfo[] NULL_VSAN_HOST_DISK_MAP_INFO_ARRAY = new com.vmware.vim25.VsanHostDiskMapInfo[ 0 ] ;
    public com.vmware.vim25.VsanHostDiskMapInfo[] VsanHostDiskMapInfo;

    public com.vmware.vim25.VsanHostDiskMapInfo[] getVsanHostDiskMapInfo() {
        if ((VsanHostDiskMapInfo) == null) {
            return (NULL_VSAN_HOST_DISK_MAP_INFO_ARRAY);
        }
        return VsanHostDiskMapInfo;
    }

    public void setVsanHostDiskMapInfo(com.vmware.vim25.VsanHostDiskMapInfo[] VsanHostDiskMapInfo) {
        this.VsanHostDiskMapInfo = VsanHostDiskMapInfo;
    }

}
