//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostProxySwitchConfig {

    private final static com.vmware.vim25.HostProxySwitchConfig[] NULL_HOST_PROXY_SWITCH_CONFIG_ARRAY = new com.vmware.vim25.HostProxySwitchConfig[ 0 ] ;
    public com.vmware.vim25.HostProxySwitchConfig[] HostProxySwitchConfig;

    public com.vmware.vim25.HostProxySwitchConfig[] getHostProxySwitchConfig() {
        if ((HostProxySwitchConfig) == null) {
            return (NULL_HOST_PROXY_SWITCH_CONFIG_ARRAY);
        }
        return HostProxySwitchConfig;
    }

    public void setHostProxySwitchConfig(com.vmware.vim25.HostProxySwitchConfig[] HostProxySwitchConfig) {
        this.HostProxySwitchConfig = HostProxySwitchConfig;
    }

}
