//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVirtualDiskId {

    private final static com.vmware.vim25.VirtualDiskId[] NULL_VIRTUAL_DISK_ID_ARRAY = new com.vmware.vim25.VirtualDiskId[ 0 ] ;
    public com.vmware.vim25.VirtualDiskId[] VirtualDiskId;

    public com.vmware.vim25.VirtualDiskId[] getVirtualDiskId() {
        if ((VirtualDiskId) == null) {
            return (NULL_VIRTUAL_DISK_ID_ARRAY);
        }
        return VirtualDiskId;
    }

    public void setVirtualDiskId(com.vmware.vim25.VirtualDiskId[] VirtualDiskId) {
        this.VirtualDiskId = VirtualDiskId;
    }

}
