//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfString {

    private final static String[] NULL_STRING_ARRAY = new String[ 0 ] ;
    public String[] string;

    public String[] getString() {
        if ((string) == null) {
            return (NULL_STRING_ARRAY);
        }
        return string;
    }

    public void setString(String[] string) {
        this.string = string;
    }

}
