//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfClusterHostRecommendation {

    private final static com.vmware.vim25.ClusterHostRecommendation[] NULL_CLUSTER_HOST_RECOMMENDATION_ARRAY = new com.vmware.vim25.ClusterHostRecommendation[ 0 ] ;
    public com.vmware.vim25.ClusterHostRecommendation[] ClusterHostRecommendation;

    public com.vmware.vim25.ClusterHostRecommendation[] getClusterHostRecommendation() {
        if ((ClusterHostRecommendation) == null) {
            return (NULL_CLUSTER_HOST_RECOMMENDATION_ARRAY);
        }
        return ClusterHostRecommendation;
    }

    public void setClusterHostRecommendation(com.vmware.vim25.ClusterHostRecommendation[] ClusterHostRecommendation) {
        this.ClusterHostRecommendation = ClusterHostRecommendation;
    }

}
