//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfUserProfile {

    private final static com.vmware.vim25.UserProfile[] NULL_USER_PROFILE_ARRAY = new com.vmware.vim25.UserProfile[ 0 ] ;
    public com.vmware.vim25.UserProfile[] UserProfile;

    public com.vmware.vim25.UserProfile[] getUserProfile() {
        if ((UserProfile) == null) {
            return (NULL_USER_PROFILE_ARRAY);
        }
        return UserProfile;
    }

    public void setUserProfile(com.vmware.vim25.UserProfile[] UserProfile) {
        this.UserProfile = UserProfile;
    }

}
