//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfStructuredCustomizations {

    private final static com.vmware.vim25.StructuredCustomizations[] NULL_STRUCTURED_CUSTOMIZATIONS_ARRAY = new com.vmware.vim25.StructuredCustomizations[ 0 ] ;
    public com.vmware.vim25.StructuredCustomizations[] StructuredCustomizations;

    public com.vmware.vim25.StructuredCustomizations[] getStructuredCustomizations() {
        if ((StructuredCustomizations) == null) {
            return (NULL_STRUCTURED_CUSTOMIZATIONS_ARRAY);
        }
        return StructuredCustomizations;
    }

    public void setStructuredCustomizations(com.vmware.vim25.StructuredCustomizations[] StructuredCustomizations) {
        this.StructuredCustomizations = StructuredCustomizations;
    }

}
