//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfDistributedVirtualSwitchManagerCompatibilityResult {

    private final static com.vmware.vim25.DistributedVirtualSwitchManagerCompatibilityResult[] NULL_DISTRIBUTED_VIRTUAL_SWITCH_MANAGER_COMPATIBILITY_RESULT_ARRAY = new com.vmware.vim25.DistributedVirtualSwitchManagerCompatibilityResult[ 0 ] ;
    public com.vmware.vim25.DistributedVirtualSwitchManagerCompatibilityResult[] DistributedVirtualSwitchManagerCompatibilityResult;

    public com.vmware.vim25.DistributedVirtualSwitchManagerCompatibilityResult[] getDistributedVirtualSwitchManagerCompatibilityResult() {
        if ((DistributedVirtualSwitchManagerCompatibilityResult) == null) {
            return (NULL_DISTRIBUTED_VIRTUAL_SWITCH_MANAGER_COMPATIBILITY_RESULT_ARRAY);
        }
        return DistributedVirtualSwitchManagerCompatibilityResult;
    }

    public void setDistributedVirtualSwitchManagerCompatibilityResult(com.vmware.vim25.DistributedVirtualSwitchManagerCompatibilityResult[] DistributedVirtualSwitchManagerCompatibilityResult) {
        this.DistributedVirtualSwitchManagerCompatibilityResult = DistributedVirtualSwitchManagerCompatibilityResult;
    }

}
