//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVirtualMachineSriovInfo {

    private final static com.vmware.vim25.VirtualMachineSriovInfo[] NULL_VIRTUAL_MACHINE_SRIOV_INFO_ARRAY = new com.vmware.vim25.VirtualMachineSriovInfo[ 0 ] ;
    public com.vmware.vim25.VirtualMachineSriovInfo[] VirtualMachineSriovInfo;

    public com.vmware.vim25.VirtualMachineSriovInfo[] getVirtualMachineSriovInfo() {
        if ((VirtualMachineSriovInfo) == null) {
            return (NULL_VIRTUAL_MACHINE_SRIOV_INFO_ARRAY);
        }
        return VirtualMachineSriovInfo;
    }

    public void setVirtualMachineSriovInfo(com.vmware.vim25.VirtualMachineSriovInfo[] VirtualMachineSriovInfo) {
        this.VirtualMachineSriovInfo = VirtualMachineSriovInfo;
    }

}
