//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVirtualMachineFloppyInfo {

    private final static com.vmware.vim25.VirtualMachineFloppyInfo[] NULL_VIRTUAL_MACHINE_FLOPPY_INFO_ARRAY = new com.vmware.vim25.VirtualMachineFloppyInfo[ 0 ] ;
    public com.vmware.vim25.VirtualMachineFloppyInfo[] VirtualMachineFloppyInfo;

    public com.vmware.vim25.VirtualMachineFloppyInfo[] getVirtualMachineFloppyInfo() {
        if ((VirtualMachineFloppyInfo) == null) {
            return (NULL_VIRTUAL_MACHINE_FLOPPY_INFO_ARRAY);
        }
        return VirtualMachineFloppyInfo;
    }

    public void setVirtualMachineFloppyInfo(com.vmware.vim25.VirtualMachineFloppyInfo[] VirtualMachineFloppyInfo) {
        this.VirtualMachineFloppyInfo = VirtualMachineFloppyInfo;
    }

}
