//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostScsiDisk {

    private final static com.vmware.vim25.HostScsiDisk[] NULL_HOST_SCSI_DISK_ARRAY = new com.vmware.vim25.HostScsiDisk[ 0 ] ;
    public com.vmware.vim25.HostScsiDisk[] HostScsiDisk;

    public com.vmware.vim25.HostScsiDisk[] getHostScsiDisk() {
        if ((HostScsiDisk) == null) {
            return (NULL_HOST_SCSI_DISK_ARRAY);
        }
        return HostScsiDisk;
    }

    public void setHostScsiDisk(com.vmware.vim25.HostScsiDisk[] HostScsiDisk) {
        this.HostScsiDisk = HostScsiDisk;
    }

}
