//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfProfilePolicyMetadata {

    private final static com.vmware.vim25.ProfilePolicyMetadata[] NULL_PROFILE_POLICY_METADATA_ARRAY = new com.vmware.vim25.ProfilePolicyMetadata[ 0 ] ;
    public com.vmware.vim25.ProfilePolicyMetadata[] ProfilePolicyMetadata;

    public com.vmware.vim25.ProfilePolicyMetadata[] getProfilePolicyMetadata() {
        if ((ProfilePolicyMetadata) == null) {
            return (NULL_PROFILE_POLICY_METADATA_ARRAY);
        }
        return ProfilePolicyMetadata;
    }

    public void setProfilePolicyMetadata(com.vmware.vim25.ProfilePolicyMetadata[] ProfilePolicyMetadata) {
        this.ProfilePolicyMetadata = ProfilePolicyMetadata;
    }

}
