//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostVirtualSwitchConfig {

    private final static com.vmware.vim25.HostVirtualSwitchConfig[] NULL_HOST_VIRTUAL_SWITCH_CONFIG_ARRAY = new com.vmware.vim25.HostVirtualSwitchConfig[ 0 ] ;
    public com.vmware.vim25.HostVirtualSwitchConfig[] HostVirtualSwitchConfig;

    public com.vmware.vim25.HostVirtualSwitchConfig[] getHostVirtualSwitchConfig() {
        if ((HostVirtualSwitchConfig) == null) {
            return (NULL_HOST_VIRTUAL_SWITCH_CONFIG_ARRAY);
        }
        return HostVirtualSwitchConfig;
    }

    public void setHostVirtualSwitchConfig(com.vmware.vim25.HostVirtualSwitchConfig[] HostVirtualSwitchConfig) {
        this.HostVirtualSwitchConfig = HostVirtualSwitchConfig;
    }

}
