//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPerfMetricId {

    private final static com.vmware.vim25.PerfMetricId[] NULL_PERF_METRIC_ID_ARRAY = new com.vmware.vim25.PerfMetricId[ 0 ] ;
    public com.vmware.vim25.PerfMetricId[] PerfMetricId;

    public com.vmware.vim25.PerfMetricId[] getPerfMetricId() {
        if ((PerfMetricId) == null) {
            return (NULL_PERF_METRIC_ID_ARRAY);
        }
        return PerfMetricId;
    }

    public void setPerfMetricId(com.vmware.vim25.PerfMetricId[] PerfMetricId) {
        this.PerfMetricId = PerfMetricId;
    }

}
