//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfSelectionSet {

    private final static com.vmware.vim25.SelectionSet[] NULL_SELECTION_SET_ARRAY = new com.vmware.vim25.SelectionSet[ 0 ] ;
    public com.vmware.vim25.SelectionSet[] SelectionSet;

    public com.vmware.vim25.SelectionSet[] getSelectionSet() {
        if ((SelectionSet) == null) {
            return (NULL_SELECTION_SET_ARRAY);
        }
        return SelectionSet;
    }

    public void setSelectionSet(com.vmware.vim25.SelectionSet[] SelectionSet) {
        this.SelectionSet = SelectionSet;
    }

}
