//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfComplianceFailure {

    private final static com.vmware.vim25.ComplianceFailure[] NULL_COMPLIANCE_FAILURE_ARRAY = new com.vmware.vim25.ComplianceFailure[ 0 ] ;
    public com.vmware.vim25.ComplianceFailure[] ComplianceFailure;

    public com.vmware.vim25.ComplianceFailure[] getComplianceFailure() {
        if ((ComplianceFailure) == null) {
            return (NULL_COMPLIANCE_FAILURE_ARRAY);
        }
        return ComplianceFailure;
    }

    public void setComplianceFailure(com.vmware.vim25.ComplianceFailure[] ComplianceFailure) {
        this.ComplianceFailure = ComplianceFailure;
    }

}
