//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVVolVmConfigFileUpdateResultFailedVmConfigFileInfo {

    private final static com.vmware.vim25.VVolVmConfigFileUpdateResultFailedVmConfigFileInfo[] NULL_V_VOL_VM_CONFIG_FILE_UPDATE_RESULT_FAILED_VM_CONFIG_FILE_INFO_ARRAY = new com.vmware.vim25.VVolVmConfigFileUpdateResultFailedVmConfigFileInfo[ 0 ] ;
    public com.vmware.vim25.VVolVmConfigFileUpdateResultFailedVmConfigFileInfo[] VVolVmConfigFileUpdateResultFailedVmConfigFileInfo;

    public com.vmware.vim25.VVolVmConfigFileUpdateResultFailedVmConfigFileInfo[] getVVolVmConfigFileUpdateResultFailedVmConfigFileInfo() {
        if ((VVolVmConfigFileUpdateResultFailedVmConfigFileInfo) == null) {
            return (NULL_V_VOL_VM_CONFIG_FILE_UPDATE_RESULT_FAILED_VM_CONFIG_FILE_INFO_ARRAY);
        }
        return VVolVmConfigFileUpdateResultFailedVmConfigFileInfo;
    }

    public void setVVolVmConfigFileUpdateResultFailedVmConfigFileInfo(com.vmware.vim25.VVolVmConfigFileUpdateResultFailedVmConfigFileInfo[] VVolVmConfigFileUpdateResultFailedVmConfigFileInfo) {
        this.VVolVmConfigFileUpdateResultFailedVmConfigFileInfo = VVolVmConfigFileUpdateResultFailedVmConfigFileInfo;
    }

}
