//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVirtualMachineSummary {

    private final static com.vmware.vim25.VirtualMachineSummary[] NULL_VIRTUAL_MACHINE_SUMMARY_ARRAY = new com.vmware.vim25.VirtualMachineSummary[ 0 ] ;
    public com.vmware.vim25.VirtualMachineSummary[] VirtualMachineSummary;

    public com.vmware.vim25.VirtualMachineSummary[] getVirtualMachineSummary() {
        if ((VirtualMachineSummary) == null) {
            return (NULL_VIRTUAL_MACHINE_SUMMARY_ARRAY);
        }
        return VirtualMachineSummary;
    }

    public void setVirtualMachineSummary(com.vmware.vim25.VirtualMachineSummary[] VirtualMachineSummary) {
        this.VirtualMachineSummary = VirtualMachineSummary;
    }

}
