//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostCpuIdInfo {

    private final static com.vmware.vim25.HostCpuIdInfo[] NULL_HOST_CPU_ID_INFO_ARRAY = new com.vmware.vim25.HostCpuIdInfo[ 0 ] ;
    public com.vmware.vim25.HostCpuIdInfo[] HostCpuIdInfo;

    public com.vmware.vim25.HostCpuIdInfo[] getHostCpuIdInfo() {
        if ((HostCpuIdInfo) == null) {
            return (NULL_HOST_CPU_ID_INFO_ARRAY);
        }
        return HostCpuIdInfo;
    }

    public void setHostCpuIdInfo(com.vmware.vim25.HostCpuIdInfo[] HostCpuIdInfo) {
        this.HostCpuIdInfo = HostCpuIdInfo;
    }

}
