//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfRelation {

    private final static com.vmware.vim25.Relation[] NULL_RELATION_ARRAY = new com.vmware.vim25.Relation[ 0 ] ;
    public com.vmware.vim25.Relation[] Relation;

    public com.vmware.vim25.Relation[] getRelation() {
        if ((Relation) == null) {
            return (NULL_RELATION_ARRAY);
        }
        return Relation;
    }

    public void setRelation(com.vmware.vim25.Relation[] Relation) {
        this.Relation = Relation;
    }

}
