//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostLowLevelProvisioningManagerFileReserveResult {

    private final static com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveResult[] NULL_HOST_LOW_LEVEL_PROVISIONING_MANAGER_FILE_RESERVE_RESULT_ARRAY = new com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveResult[ 0 ] ;
    public com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveResult[] HostLowLevelProvisioningManagerFileReserveResult;

    public com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveResult[] getHostLowLevelProvisioningManagerFileReserveResult() {
        if ((HostLowLevelProvisioningManagerFileReserveResult) == null) {
            return (NULL_HOST_LOW_LEVEL_PROVISIONING_MANAGER_FILE_RESERVE_RESULT_ARRAY);
        }
        return HostLowLevelProvisioningManagerFileReserveResult;
    }

    public void setHostLowLevelProvisioningManagerFileReserveResult(com.vmware.vim25.HostLowLevelProvisioningManagerFileReserveResult[] HostLowLevelProvisioningManagerFileReserveResult) {
        this.HostLowLevelProvisioningManagerFileReserveResult = HostLowLevelProvisioningManagerFileReserveResult;
    }

}
