//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfLicenseReservationInfo {

    private final static com.vmware.vim25.LicenseReservationInfo[] NULL_LICENSE_RESERVATION_INFO_ARRAY = new com.vmware.vim25.LicenseReservationInfo[ 0 ] ;
    public com.vmware.vim25.LicenseReservationInfo[] LicenseReservationInfo;

    public com.vmware.vim25.LicenseReservationInfo[] getLicenseReservationInfo() {
        if ((LicenseReservationInfo) == null) {
            return (NULL_LICENSE_RESERVATION_INFO_ARRAY);
        }
        return LicenseReservationInfo;
    }

    public void setLicenseReservationInfo(com.vmware.vim25.LicenseReservationInfo[] LicenseReservationInfo) {
        this.LicenseReservationInfo = LicenseReservationInfo;
    }

}
