//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfExtensionFaultTypeInfo {

    private final static com.vmware.vim25.ExtensionFaultTypeInfo[] NULL_EXTENSION_FAULT_TYPE_INFO_ARRAY = new com.vmware.vim25.ExtensionFaultTypeInfo[ 0 ] ;
    public com.vmware.vim25.ExtensionFaultTypeInfo[] ExtensionFaultTypeInfo;

    public com.vmware.vim25.ExtensionFaultTypeInfo[] getExtensionFaultTypeInfo() {
        if ((ExtensionFaultTypeInfo) == null) {
            return (NULL_EXTENSION_FAULT_TYPE_INFO_ARRAY);
        }
        return ExtensionFaultTypeInfo;
    }

    public void setExtensionFaultTypeInfo(com.vmware.vim25.ExtensionFaultTypeInfo[] ExtensionFaultTypeInfo) {
        this.ExtensionFaultTypeInfo = ExtensionFaultTypeInfo;
    }

}
