//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfTaskInfo {

    private final static com.vmware.vim25.TaskInfo[] NULL_TASK_INFO_ARRAY = new com.vmware.vim25.TaskInfo[ 0 ] ;
    public com.vmware.vim25.TaskInfo[] TaskInfo;

    public com.vmware.vim25.TaskInfo[] getTaskInfo() {
        if ((TaskInfo) == null) {
            return (NULL_TASK_INFO_ARRAY);
        }
        return TaskInfo;
    }

    public void setTaskInfo(com.vmware.vim25.TaskInfo[] TaskInfo) {
        this.TaskInfo = TaskInfo;
    }

}
