//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfHostOpaqueSwitch {

    private final static com.vmware.vim25.HostOpaqueSwitch[] NULL_HOST_OPAQUE_SWITCH_ARRAY = new com.vmware.vim25.HostOpaqueSwitch[ 0 ] ;
    public com.vmware.vim25.HostOpaqueSwitch[] HostOpaqueSwitch;

    public com.vmware.vim25.HostOpaqueSwitch[] getHostOpaqueSwitch() {
        if ((HostOpaqueSwitch) == null) {
            return (NULL_HOST_OPAQUE_SWITCH_ARRAY);
        }
        return HostOpaqueSwitch;
    }

    public void setHostOpaqueSwitch(com.vmware.vim25.HostOpaqueSwitch[] HostOpaqueSwitch) {
        this.HostOpaqueSwitch = HostOpaqueSwitch;
    }

}
