//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfAlarmTriggeringActionTransitionSpec {

    private final static com.vmware.vim25.AlarmTriggeringActionTransitionSpec[] NULL_ALARM_TRIGGERING_ACTION_TRANSITION_SPEC_ARRAY = new com.vmware.vim25.AlarmTriggeringActionTransitionSpec[ 0 ] ;
    public com.vmware.vim25.AlarmTriggeringActionTransitionSpec[] AlarmTriggeringActionTransitionSpec;

    public com.vmware.vim25.AlarmTriggeringActionTransitionSpec[] getAlarmTriggeringActionTransitionSpec() {
        if ((AlarmTriggeringActionTransitionSpec) == null) {
            return (NULL_ALARM_TRIGGERING_ACTION_TRANSITION_SPEC_ARRAY);
        }
        return AlarmTriggeringActionTransitionSpec;
    }

    public void setAlarmTriggeringActionTransitionSpec(com.vmware.vim25.AlarmTriggeringActionTransitionSpec[] AlarmTriggeringActionTransitionSpec) {
        this.AlarmTriggeringActionTransitionSpec = AlarmTriggeringActionTransitionSpec;
    }

}
