//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfBoolean {

    private final static boolean[] NULL__BOOLEAN_ARRAY = new boolean[ 0 ] ;
    public boolean[] _boolean;

    public boolean[] get_boolean() {
        if ((_boolean) == null) {
            return (NULL__BOOLEAN_ARRAY);
        }
        return _boolean;
    }

    public void set_boolean(boolean[] _boolean) {
        this._boolean = _boolean;
    }

}
