//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfVASAStorageArray {

    private final static com.vmware.vim25.VASAStorageArray[] NULL_VASA_STORAGE_ARRAY_ARRAY = new com.vmware.vim25.VASAStorageArray[ 0 ] ;
    public com.vmware.vim25.VASAStorageArray[] VASAStorageArray;

    public com.vmware.vim25.VASAStorageArray[] getVasaStorageArray() {
        if ((VASAStorageArray) == null) {
            return (NULL_VASA_STORAGE_ARRAY_ARRAY);
        }
        return VASAStorageArray;
    }

    public void setVasaStorageArray(com.vmware.vim25.VASAStorageArray[] VASAStorageArray) {
        this.VASAStorageArray = VASAStorageArray;
    }

}
