//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class AuthorizationRole
    extends DynamicData
{

    public int roleId;
    public boolean system;
    public String name;
    public Description info;
    private final static String[] NULL_PRIVILEGE_ARRAY = new String[ 0 ] ;
    public String[] privilege;

    public int getRoleId() {
        return roleId;
    }

    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    public boolean getSystem() {
        return system;
    }

    public void setSystem(boolean system) {
        this.system = system;
    }

    public boolean isSystem() {
        return system;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Description getInfo() {
        return info;
    }

    public void setInfo(Description info) {
        this.info = info;
    }

    public String[] getPrivilege() {
        if ((privilege) == null) {
            return (NULL_PRIVILEGE_ARRAY);
        }
        return privilege;
    }

    public void setPrivilege(String[] privilege) {
        this.privilege = privilege;
    }

}
