//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ClusterConfigSpec
    extends DynamicData
{

    public ClusterDasConfigInfo dasConfig;
    private final static ClusterDasVmConfigSpec[] NULL_DAS_VM_CONFIG_SPEC_ARRAY = new ClusterDasVmConfigSpec[ 0 ] ;
    public ClusterDasVmConfigSpec[] dasVmConfigSpec;
    public ClusterDrsConfigInfo drsConfig;
    private final static ClusterDrsVmConfigSpec[] NULL_DRS_VM_CONFIG_SPEC_ARRAY = new ClusterDrsVmConfigSpec[ 0 ] ;
    public ClusterDrsVmConfigSpec[] drsVmConfigSpec;
    private final static ClusterRuleSpec[] NULL_RULES_SPEC_ARRAY = new ClusterRuleSpec[ 0 ] ;
    public ClusterRuleSpec[] rulesSpec;

    public ClusterDasConfigInfo getDasConfig() {
        return dasConfig;
    }

    public void setDasConfig(ClusterDasConfigInfo dasConfig) {
        this.dasConfig = dasConfig;
    }

    public ClusterDasVmConfigSpec[] getDasVmConfigSpec() {
        if ((dasVmConfigSpec) == null) {
            return (NULL_DAS_VM_CONFIG_SPEC_ARRAY);
        }
        return dasVmConfigSpec;
    }

    public void setDasVmConfigSpec(ClusterDasVmConfigSpec[] dasVmConfigSpec) {
        this.dasVmConfigSpec = dasVmConfigSpec;
    }

    public ClusterDrsConfigInfo getDrsConfig() {
        return drsConfig;
    }

    public void setDrsConfig(ClusterDrsConfigInfo drsConfig) {
        this.drsConfig = drsConfig;
    }

    public ClusterDrsVmConfigSpec[] getDrsVmConfigSpec() {
        if ((drsVmConfigSpec) == null) {
            return (NULL_DRS_VM_CONFIG_SPEC_ARRAY);
        }
        return drsVmConfigSpec;
    }

    public void setDrsVmConfigSpec(ClusterDrsVmConfigSpec[] drsVmConfigSpec) {
        this.drsVmConfigSpec = drsVmConfigSpec;
    }

    public ClusterRuleSpec[] getRulesSpec() {
        if ((rulesSpec) == null) {
            return (NULL_RULES_SPEC_ARRAY);
        }
        return rulesSpec;
    }

    public void setRulesSpec(ClusterRuleSpec[] rulesSpec) {
        this.rulesSpec = rulesSpec;
    }

}
