//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class ClusterDasFdmHostState
    extends DynamicData
{

    public String state;
    public ManagedObjectReference stateReporter;

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public ManagedObjectReference getStateReporter() {
        return stateReporter;
    }

    public void setStateReporter(ManagedObjectReference stateReporter) {
        this.stateReporter = stateReporter;
    }

}
