//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class CompositePolicyOption
    extends PolicyOption
{

    private final static PolicyOption[] NULL_OPTION_ARRAY = new PolicyOption[ 0 ] ;
    public PolicyOption[] option;

    public PolicyOption[] getOption() {
        if ((option) == null) {
            return (NULL_OPTION_ARRAY);
        }
        return option;
    }

    public void setOption(PolicyOption[] option) {
        this.option = option;
    }

}
