//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class CryptoManagerKmipServerCertInfo
    extends DynamicData
{

    public String certificate;
    public CryptoManagerKmipCertificateInfo certInfo;
    public Boolean clientTrustServer;

    public String getCertificate() {
        return certificate;
    }

    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    public CryptoManagerKmipCertificateInfo getCertInfo() {
        return certInfo;
    }

    public void setCertInfo(CryptoManagerKmipCertificateInfo certInfo) {
        this.certInfo = certInfo;
    }

    public Boolean getClientTrustServer() {
        return clientTrustServer;
    }

    public void setClientTrustServer(Boolean clientTrustServer) {
        this.clientTrustServer = clientTrustServer;
    }

    public Boolean isClientTrustServer() {
        return clientTrustServer;
    }

}
