//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class DatastoreOption
    extends DynamicData
{

    private final static VirtualMachineDatastoreVolumeOption[] NULL_UNSUPPORTED_VOLUMES_ARRAY = new VirtualMachineDatastoreVolumeOption[ 0 ] ;
    public VirtualMachineDatastoreVolumeOption[] unsupportedVolumes;

    public VirtualMachineDatastoreVolumeOption[] getUnsupportedVolumes() {
        if ((unsupportedVolumes) == null) {
            return (NULL_UNSUPPORTED_VOLUMES_ARRAY);
        }
        return unsupportedVolumes;
    }

    public void setUnsupportedVolumes(VirtualMachineDatastoreVolumeOption[] unsupportedVolumes) {
        this.unsupportedVolumes = unsupportedVolumes;
    }

}
