//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class DVPortState
    extends DynamicData
{

    public DVPortStatus runtimeInfo;
    public DistributedVirtualSwitchPortStatistics stats;
    private final static DistributedVirtualSwitchKeyedOpaqueBlob[] NULL_VENDOR_SPECIFIC_STATE_ARRAY = new DistributedVirtualSwitchKeyedOpaqueBlob[ 0 ] ;
    public DistributedVirtualSwitchKeyedOpaqueBlob[] vendorSpecificState;

    public DVPortStatus getRuntimeInfo() {
        return runtimeInfo;
    }

    public void setRuntimeInfo(DVPortStatus runtimeInfo) {
        this.runtimeInfo = runtimeInfo;
    }

    public DistributedVirtualSwitchPortStatistics getStats() {
        return stats;
    }

    public void setStats(DistributedVirtualSwitchPortStatistics stats) {
        this.stats = stats;
    }

    public DistributedVirtualSwitchKeyedOpaqueBlob[] getVendorSpecificState() {
        if ((vendorSpecificState) == null) {
            return (NULL_VENDOR_SPECIFIC_STATE_ARRAY);
        }
        return vendorSpecificState;
    }

    public void setVendorSpecificState(DistributedVirtualSwitchKeyedOpaqueBlob[] vendorSpecificState) {
        this.vendorSpecificState = vendorSpecificState;
    }

}
