//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class DVPortgroupPolicy
    extends DynamicData
{

    public boolean blockOverrideAllowed;
    public boolean shapingOverrideAllowed;
    public boolean vendorConfigOverrideAllowed;
    public boolean livePortMovingAllowed;
    public boolean portConfigResetAtDisconnect;
    public Boolean networkResourcePoolOverrideAllowed;
    public Boolean trafficFilterOverrideAllowed;

    public boolean getBlockOverrideAllowed() {
        return blockOverrideAllowed;
    }

    public void setBlockOverrideAllowed(boolean blockOverrideAllowed) {
        this.blockOverrideAllowed = blockOverrideAllowed;
    }

    public boolean isBlockOverrideAllowed() {
        return blockOverrideAllowed;
    }

    public boolean getShapingOverrideAllowed() {
        return shapingOverrideAllowed;
    }

    public void setShapingOverrideAllowed(boolean shapingOverrideAllowed) {
        this.shapingOverrideAllowed = shapingOverrideAllowed;
    }

    public boolean isShapingOverrideAllowed() {
        return shapingOverrideAllowed;
    }

    public boolean getVendorConfigOverrideAllowed() {
        return vendorConfigOverrideAllowed;
    }

    public void setVendorConfigOverrideAllowed(boolean vendorConfigOverrideAllowed) {
        this.vendorConfigOverrideAllowed = vendorConfigOverrideAllowed;
    }

    public boolean isVendorConfigOverrideAllowed() {
        return vendorConfigOverrideAllowed;
    }

    public boolean getLivePortMovingAllowed() {
        return livePortMovingAllowed;
    }

    public void setLivePortMovingAllowed(boolean livePortMovingAllowed) {
        this.livePortMovingAllowed = livePortMovingAllowed;
    }

    public boolean isLivePortMovingAllowed() {
        return livePortMovingAllowed;
    }

    public boolean getPortConfigResetAtDisconnect() {
        return portConfigResetAtDisconnect;
    }

    public void setPortConfigResetAtDisconnect(boolean portConfigResetAtDisconnect) {
        this.portConfigResetAtDisconnect = portConfigResetAtDisconnect;
    }

    public boolean isPortConfigResetAtDisconnect() {
        return portConfigResetAtDisconnect;
    }

    public Boolean getNetworkResourcePoolOverrideAllowed() {
        return networkResourcePoolOverrideAllowed;
    }

    public void setNetworkResourcePoolOverrideAllowed(Boolean networkResourcePoolOverrideAllowed) {
        this.networkResourcePoolOverrideAllowed = networkResourcePoolOverrideAllowed;
    }

    public Boolean isNetworkResourcePoolOverrideAllowed() {
        return networkResourcePoolOverrideAllowed;
    }

    public Boolean getTrafficFilterOverrideAllowed() {
        return trafficFilterOverrideAllowed;
    }

    public void setTrafficFilterOverrideAllowed(Boolean trafficFilterOverrideAllowed) {
        this.trafficFilterOverrideAllowed = trafficFilterOverrideAllowed;
    }

    public Boolean isTrafficFilterOverrideAllowed() {
        return trafficFilterOverrideAllowed;
    }

}
