//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class DVPortgroupConfigSpec
    extends DynamicData
{

    public String configVersion;
    public String name;
    public Integer numPorts;
    public String portNameFormat;
    public DVPortSetting defaultPortConfig;
    public String description;
    public String type;
    private final static ManagedObjectReference[] NULL_SCOPE_ARRAY = new ManagedObjectReference[ 0 ] ;
    public ManagedObjectReference[] scope;
    public DVPortgroupPolicy policy;
    private final static DistributedVirtualSwitchKeyedOpaqueBlob[] NULL_VENDOR_SPECIFIC_CONFIG_ARRAY = new DistributedVirtualSwitchKeyedOpaqueBlob[ 0 ] ;
    public DistributedVirtualSwitchKeyedOpaqueBlob[] vendorSpecificConfig;
    public Boolean autoExpand;
    public String vmVnicNetworkResourcePoolKey;

    public String getConfigVersion() {
        return configVersion;
    }

    public void setConfigVersion(String configVersion) {
        this.configVersion = configVersion;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getNumPorts() {
        return numPorts;
    }

    public void setNumPorts(Integer numPorts) {
        this.numPorts = numPorts;
    }

    public String getPortNameFormat() {
        return portNameFormat;
    }

    public void setPortNameFormat(String portNameFormat) {
        this.portNameFormat = portNameFormat;
    }

    public DVPortSetting getDefaultPortConfig() {
        return defaultPortConfig;
    }

    public void setDefaultPortConfig(DVPortSetting defaultPortConfig) {
        this.defaultPortConfig = defaultPortConfig;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public ManagedObjectReference[] getScope() {
        if ((scope) == null) {
            return (NULL_SCOPE_ARRAY);
        }
        return scope;
    }

    public void setScope(ManagedObjectReference[] scope) {
        this.scope = scope;
    }

    public DVPortgroupPolicy getPolicy() {
        return policy;
    }

    public void setPolicy(DVPortgroupPolicy policy) {
        this.policy = policy;
    }

    public DistributedVirtualSwitchKeyedOpaqueBlob[] getVendorSpecificConfig() {
        if ((vendorSpecificConfig) == null) {
            return (NULL_VENDOR_SPECIFIC_CONFIG_ARRAY);
        }
        return vendorSpecificConfig;
    }

    public void setVendorSpecificConfig(DistributedVirtualSwitchKeyedOpaqueBlob[] vendorSpecificConfig) {
        this.vendorSpecificConfig = vendorSpecificConfig;
    }

    public Boolean getAutoExpand() {
        return autoExpand;
    }

    public void setAutoExpand(Boolean autoExpand) {
        this.autoExpand = autoExpand;
    }

    public Boolean isAutoExpand() {
        return autoExpand;
    }

    public String getVmVnicNetworkResourcePoolKey() {
        return vmVnicNetworkResourcePoolKey;
    }

    public void setVmVnicNetworkResourcePoolKey(String vmVnicNetworkResourcePoolKey) {
        this.vmVnicNetworkResourcePoolKey = vmVnicNetworkResourcePoolKey;
    }

}
