//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ExtensionManagerIpAllocationUsage
    extends DynamicData
{

    public String extensionKey;
    public int numAddresses;

    public String getExtensionKey() {
        return extensionKey;
    }

    public void setExtensionKey(String extensionKey) {
        this.extensionKey = extensionKey;
    }

    public int getNumAddresses() {
        return numAddresses;
    }

    public void setNumAddresses(int numAddresses) {
        this.numAddresses = numAddresses;
    }

}
