//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ExtensionServerInfo
    extends DynamicData
{

    public String url;
    public Description description;
    public String company;
    public String type;
    private final static String[] NULL_ADMIN_EMAIL_ARRAY = new String[ 0 ] ;
    public String[] adminEmail;
    public String serverThumbprint;

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Description getDescription() {
        return description;
    }

    public void setDescription(Description description) {
        this.description = description;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String[] getAdminEmail() {
        if ((adminEmail) == null) {
            return (NULL_ADMIN_EMAIL_ARRAY);
        }
        return adminEmail;
    }

    public void setAdminEmail(String[] adminEmail) {
        this.adminEmail = adminEmail;
    }

    public String getServerThumbprint() {
        return serverThumbprint;
    }

    public void setServerThumbprint(String serverThumbprint) {
        this.serverThumbprint = serverThumbprint;
    }

}
