//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class FailToEnableSPBM
    extends NotEnoughLicenses
{

    public ManagedObjectReference cs;
    public String csName;
    private final static ComputeResourceHostSPBMLicenseInfo[] NULL_HOST_LICENSE_STATES_ARRAY = new ComputeResourceHostSPBMLicenseInfo[ 0 ] ;
    public ComputeResourceHostSPBMLicenseInfo[] hostLicenseStates;

    public ManagedObjectReference getCs() {
        return cs;
    }

    public void setCs(ManagedObjectReference cs) {
        this.cs = cs;
    }

    public String getCsName() {
        return csName;
    }

    public void setCsName(String csName) {
        this.csName = csName;
    }

    public ComputeResourceHostSPBMLicenseInfo[] getHostLicenseStates() {
        if ((hostLicenseStates) == null) {
            return (NULL_HOST_LICENSE_STATES_ARRAY);
        }
        return hostLicenseStates;
    }

    public void setHostLicenseStates(ComputeResourceHostSPBMLicenseInfo[] hostLicenseStates) {
        this.hostLicenseStates = hostLicenseStates;
    }

}
