//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class FailoverNodeInfo
    extends DynamicData
{

    public CustomizationIPSettings clusterIpSettings;
    public CustomizationIPSettings failoverIp;
    public String biosUuid;

    public CustomizationIPSettings getClusterIpSettings() {
        return clusterIpSettings;
    }

    public void setClusterIpSettings(CustomizationIPSettings clusterIpSettings) {
        this.clusterIpSettings = clusterIpSettings;
    }

    public CustomizationIPSettings getFailoverIp() {
        return failoverIp;
    }

    public void setFailoverIp(CustomizationIPSettings failoverIp) {
        this.failoverIp = failoverIp;
    }

    public String getBiosUuid() {
        return biosUuid;
    }

    public void setBiosUuid(String biosUuid) {
        this.biosUuid = biosUuid;
    }

}
