//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class FeatureRequirementsNotMet
    extends VirtualHardwareCompatibilityIssue
{

    private final static VirtualMachineFeatureRequirement[] NULL_FEATURE_REQUIREMENT_ARRAY = new VirtualMachineFeatureRequirement[ 0 ] ;
    public VirtualMachineFeatureRequirement[] featureRequirement;
    public ManagedObjectReference vm;
    public ManagedObjectReference host;

    public VirtualMachineFeatureRequirement[] getFeatureRequirement() {
        if ((featureRequirement) == null) {
            return (NULL_FEATURE_REQUIREMENT_ARRAY);
        }
        return featureRequirement;
    }

    public void setFeatureRequirement(VirtualMachineFeatureRequirement[] featureRequirement) {
        this.featureRequirement = featureRequirement;
    }

    public ManagedObjectReference getVm() {
        return vm;
    }

    public void setVm(ManagedObjectReference vm) {
        this.vm = vm;
    }

    public ManagedObjectReference getHost() {
        return host;
    }

    public void setHost(ManagedObjectReference host) {
        this.host = host;
    }

}
