//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class GuestAliases
    extends DynamicData
{

    public String base64Cert;
    private final static GuestAuthAliasInfo[] NULL_ALIASES_ARRAY = new GuestAuthAliasInfo[ 0 ] ;
    public GuestAuthAliasInfo[] aliases;

    public String getBase64Cert() {
        return base64Cert;
    }

    public void setBase64Cert(String base64Cert) {
        this.base64Cert = base64Cert;
    }

    public GuestAuthAliasInfo[] getAliases() {
        if ((aliases) == null) {
            return (NULL_ALIASES_ARRAY);
        }
        return aliases;
    }

    public void setAliases(GuestAuthAliasInfo[] aliases) {
        this.aliases = aliases;
    }

}
