//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class GuestRegKeyRecordSpec
    extends DynamicData
{

    public GuestRegKeySpec key;
    public LocalizedMethodFault fault;

    public GuestRegKeySpec getKey() {
        return key;
    }

    public void setKey(GuestRegKeySpec key) {
        this.key = key;
    }

    public LocalizedMethodFault getFault() {
        return fault;
    }

    public void setFault(LocalizedMethodFault fault) {
        this.fault = fault;
    }

}
