//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostCapability
    extends DynamicData
{

    public boolean recursiveResourcePoolsSupported;
    public boolean cpuMemoryResourceConfigurationSupported;
    public boolean rebootSupported;
    public boolean shutdownSupported;
    public boolean vmotionSupported;
    public boolean standbySupported;
    public Boolean ipmiSupported;
    public Integer maxSupportedVMs;
    public Integer maxRunningVMs;
    public Integer maxSupportedVcpus;
    public Integer maxRegisteredVMs;
    public boolean datastorePrincipalSupported;
    public boolean sanSupported;
    public boolean nfsSupported;
    public boolean iscsiSupported;
    public boolean vlanTaggingSupported;
    public boolean nicTeamingSupported;
    public boolean highGuestMemSupported;
    public boolean maintenanceModeSupported;
    public boolean suspendedRelocateSupported;
    public boolean restrictedSnapshotRelocateSupported;
    public boolean perVmSwapFiles;
    public boolean localSwapDatastoreSupported;
    public boolean unsharedSwapVMotionSupported;
    public boolean backgroundSnapshotsSupported;
    public boolean preAssignedPCIUnitNumbersSupported;
    public boolean screenshotSupported;
    public boolean scaledScreenshotSupported;
    public Boolean storageVMotionSupported;
    public Boolean vmotionWithStorageVMotionSupported;
    public Boolean vmotionAcrossNetworkSupported;
    public Integer maxNumDisksSVMotion;
    public Boolean hbrNicSelectionSupported;
    public Boolean vrNfcNicSelectionSupported;
    public Boolean recordReplaySupported;
    public Boolean ftSupported;
    public String replayUnsupportedReason;
    private final static String[] NULL_REPLAY_COMPATIBILITY_ISSUES_ARRAY = new String[ 0 ] ;
    public String[] replayCompatibilityIssues;
    public Boolean smpFtSupported;
    private final static String[] NULL_FT_COMPATIBILITY_ISSUES_ARRAY = new String[ 0 ] ;
    public String[] ftCompatibilityIssues;
    private final static String[] NULL_SMP_FT_COMPATIBILITY_ISSUES_ARRAY = new String[ 0 ] ;
    public String[] smpFtCompatibilityIssues;
    public Integer maxVcpusPerFtVm;
    public Boolean loginBySSLThumbprintSupported;
    public Boolean cloneFromSnapshotSupported;
    public Boolean deltaDiskBackingsSupported;
    public Boolean perVMNetworkTrafficShapingSupported;
    public Boolean tpmSupported;
    public String tpmVersion;
    public Boolean txtEnabled;
    private final static HostCpuIdInfo[] NULL_SUPPORTED_CPU_FEATURE_ARRAY = new HostCpuIdInfo[ 0 ] ;
    public HostCpuIdInfo[] supportedCpuFeature;
    public Boolean virtualExecUsageSupported;
    public Boolean storageIORMSupported;
    public Boolean vmDirectPathGen2Supported;
    private final static String[] NULL_VM_DIRECT_PATH_GEN2_UNSUPPORTED_REASON_ARRAY = new String[ 0 ] ;
    public String[] vmDirectPathGen2UnsupportedReason;
    public String vmDirectPathGen2UnsupportedReasonExtended;
    private final static int[] NULL_SUPPORTED_VMFS_MAJOR_VERSION_ARRAY = new int[ 0 ] ;
    public int[] supportedVmfsMajorVersion;
    public Boolean vStorageCapable;
    public Boolean snapshotRelayoutSupported;
    public Boolean firewallIpRulesSupported;
    public Boolean servicePackageInfoSupported;
    public Integer maxHostRunningVms;
    public Integer maxHostSupportedVcpus;
    public Boolean vmfsDatastoreMountCapable;
    public Boolean eightPlusHostVmfsSharedAccessSupported;
    public Boolean nestedHVSupported;
    public Boolean vPMCSupported;
    public Boolean interVMCommunicationThroughVMCISupported;
    public Boolean scheduledHardwareUpgradeSupported;
    public Boolean featureCapabilitiesSupported;
    public Boolean latencySensitivitySupported;
    public Boolean storagePolicySupported;
    public Boolean accel3dSupported;
    public Boolean reliableMemoryAware;
    public Boolean multipleNetworkStackInstanceSupported;
    public Boolean messageBusProxySupported;
    public Boolean vsanSupported;
    public Boolean vFlashSupported;
    public Boolean hostAccessManagerSupported;
    public Boolean provisioningNicSelectionSupported;
    public Boolean nfs41Supported;
    public Boolean nfs41Krb5iSupported;
    public Boolean turnDiskLocatorLedSupported;
    public Boolean virtualVolumeDatastoreSupported;
    public Boolean markAsSsdSupported;
    public Boolean markAsLocalSupported;
    public Boolean smartCardAuthenticationSupported;
    public Boolean pMemSupported;
    public Boolean pMemSnapshotSupported;
    public Boolean cryptoSupported;
    public Boolean oneKVolumeAPIsSupported;
    public Boolean gatewayOnNicSupported;
    public Boolean upitSupported;
    public Boolean cpuHwMmuSupported;
    public Boolean encryptedVMotionSupported;
    public Boolean encryptionChangeOnAddRemoveSupported;
    public Boolean encryptionHotOperationSupported;
    public Boolean encryptionWithSnapshotsSupported;
    public Boolean encryptionFaultToleranceSupported;
    public Boolean encryptionMemorySaveSupported;
    public Boolean encryptionRDMSupported;
    public Boolean encryptionVFlashSupported;
    public Boolean encryptionCBRCSupported;
    public Boolean encryptionHBRSupported;
    public Boolean ftEfiSupported;
    public String unmapMethodSupported;
    public Integer maxMemMBPerFtVm;
    public Boolean virtualMmuUsageIgnored;
    public Boolean virtualExecUsageIgnored;
    public Boolean vmCreateDateSupported;
    public Boolean vmfs3EOLSupported;
    public Boolean ftVmcpSupported;

    public boolean getRecursiveResourcePoolsSupported() {
        return recursiveResourcePoolsSupported;
    }

    public void setRecursiveResourcePoolsSupported(boolean recursiveResourcePoolsSupported) {
        this.recursiveResourcePoolsSupported = recursiveResourcePoolsSupported;
    }

    public boolean isRecursiveResourcePoolsSupported() {
        return recursiveResourcePoolsSupported;
    }

    public boolean getCpuMemoryResourceConfigurationSupported() {
        return cpuMemoryResourceConfigurationSupported;
    }

    public void setCpuMemoryResourceConfigurationSupported(boolean cpuMemoryResourceConfigurationSupported) {
        this.cpuMemoryResourceConfigurationSupported = cpuMemoryResourceConfigurationSupported;
    }

    public boolean isCpuMemoryResourceConfigurationSupported() {
        return cpuMemoryResourceConfigurationSupported;
    }

    public boolean getRebootSupported() {
        return rebootSupported;
    }

    public void setRebootSupported(boolean rebootSupported) {
        this.rebootSupported = rebootSupported;
    }

    public boolean isRebootSupported() {
        return rebootSupported;
    }

    public boolean getShutdownSupported() {
        return shutdownSupported;
    }

    public void setShutdownSupported(boolean shutdownSupported) {
        this.shutdownSupported = shutdownSupported;
    }

    public boolean isShutdownSupported() {
        return shutdownSupported;
    }

    public boolean getVmotionSupported() {
        return vmotionSupported;
    }

    public void setVmotionSupported(boolean vmotionSupported) {
        this.vmotionSupported = vmotionSupported;
    }

    public boolean isVmotionSupported() {
        return vmotionSupported;
    }

    public boolean getStandbySupported() {
        return standbySupported;
    }

    public void setStandbySupported(boolean standbySupported) {
        this.standbySupported = standbySupported;
    }

    public boolean isStandbySupported() {
        return standbySupported;
    }

    public Boolean getIpmiSupported() {
        return ipmiSupported;
    }

    public void setIpmiSupported(Boolean ipmiSupported) {
        this.ipmiSupported = ipmiSupported;
    }

    public Boolean isIpmiSupported() {
        return ipmiSupported;
    }

    public Integer getMaxSupportedVMs() {
        return maxSupportedVMs;
    }

    public void setMaxSupportedVMs(Integer maxSupportedVMs) {
        this.maxSupportedVMs = maxSupportedVMs;
    }

    public Integer getMaxRunningVMs() {
        return maxRunningVMs;
    }

    public void setMaxRunningVMs(Integer maxRunningVMs) {
        this.maxRunningVMs = maxRunningVMs;
    }

    public Integer getMaxSupportedVcpus() {
        return maxSupportedVcpus;
    }

    public void setMaxSupportedVcpus(Integer maxSupportedVcpus) {
        this.maxSupportedVcpus = maxSupportedVcpus;
    }

    public Integer getMaxRegisteredVMs() {
        return maxRegisteredVMs;
    }

    public void setMaxRegisteredVMs(Integer maxRegisteredVMs) {
        this.maxRegisteredVMs = maxRegisteredVMs;
    }

    public boolean getDatastorePrincipalSupported() {
        return datastorePrincipalSupported;
    }

    public void setDatastorePrincipalSupported(boolean datastorePrincipalSupported) {
        this.datastorePrincipalSupported = datastorePrincipalSupported;
    }

    public boolean isDatastorePrincipalSupported() {
        return datastorePrincipalSupported;
    }

    public boolean getSanSupported() {
        return sanSupported;
    }

    public void setSanSupported(boolean sanSupported) {
        this.sanSupported = sanSupported;
    }

    public boolean isSanSupported() {
        return sanSupported;
    }

    public boolean getNfsSupported() {
        return nfsSupported;
    }

    public void setNfsSupported(boolean nfsSupported) {
        this.nfsSupported = nfsSupported;
    }

    public boolean isNfsSupported() {
        return nfsSupported;
    }

    public boolean getIscsiSupported() {
        return iscsiSupported;
    }

    public void setIscsiSupported(boolean iscsiSupported) {
        this.iscsiSupported = iscsiSupported;
    }

    public boolean isIscsiSupported() {
        return iscsiSupported;
    }

    public boolean getVlanTaggingSupported() {
        return vlanTaggingSupported;
    }

    public void setVlanTaggingSupported(boolean vlanTaggingSupported) {
        this.vlanTaggingSupported = vlanTaggingSupported;
    }

    public boolean isVlanTaggingSupported() {
        return vlanTaggingSupported;
    }

    public boolean getNicTeamingSupported() {
        return nicTeamingSupported;
    }

    public void setNicTeamingSupported(boolean nicTeamingSupported) {
        this.nicTeamingSupported = nicTeamingSupported;
    }

    public boolean isNicTeamingSupported() {
        return nicTeamingSupported;
    }

    public boolean getHighGuestMemSupported() {
        return highGuestMemSupported;
    }

    public void setHighGuestMemSupported(boolean highGuestMemSupported) {
        this.highGuestMemSupported = highGuestMemSupported;
    }

    public boolean isHighGuestMemSupported() {
        return highGuestMemSupported;
    }

    public boolean getMaintenanceModeSupported() {
        return maintenanceModeSupported;
    }

    public void setMaintenanceModeSupported(boolean maintenanceModeSupported) {
        this.maintenanceModeSupported = maintenanceModeSupported;
    }

    public boolean isMaintenanceModeSupported() {
        return maintenanceModeSupported;
    }

    public boolean getSuspendedRelocateSupported() {
        return suspendedRelocateSupported;
    }

    public void setSuspendedRelocateSupported(boolean suspendedRelocateSupported) {
        this.suspendedRelocateSupported = suspendedRelocateSupported;
    }

    public boolean isSuspendedRelocateSupported() {
        return suspendedRelocateSupported;
    }

    public boolean getRestrictedSnapshotRelocateSupported() {
        return restrictedSnapshotRelocateSupported;
    }

    public void setRestrictedSnapshotRelocateSupported(boolean restrictedSnapshotRelocateSupported) {
        this.restrictedSnapshotRelocateSupported = restrictedSnapshotRelocateSupported;
    }

    public boolean isRestrictedSnapshotRelocateSupported() {
        return restrictedSnapshotRelocateSupported;
    }

    public boolean getPerVmSwapFiles() {
        return perVmSwapFiles;
    }

    public void setPerVmSwapFiles(boolean perVmSwapFiles) {
        this.perVmSwapFiles = perVmSwapFiles;
    }

    public boolean isPerVmSwapFiles() {
        return perVmSwapFiles;
    }

    public boolean getLocalSwapDatastoreSupported() {
        return localSwapDatastoreSupported;
    }

    public void setLocalSwapDatastoreSupported(boolean localSwapDatastoreSupported) {
        this.localSwapDatastoreSupported = localSwapDatastoreSupported;
    }

    public boolean isLocalSwapDatastoreSupported() {
        return localSwapDatastoreSupported;
    }

    public boolean getUnsharedSwapVMotionSupported() {
        return unsharedSwapVMotionSupported;
    }

    public void setUnsharedSwapVMotionSupported(boolean unsharedSwapVMotionSupported) {
        this.unsharedSwapVMotionSupported = unsharedSwapVMotionSupported;
    }

    public boolean isUnsharedSwapVMotionSupported() {
        return unsharedSwapVMotionSupported;
    }

    public boolean getBackgroundSnapshotsSupported() {
        return backgroundSnapshotsSupported;
    }

    public void setBackgroundSnapshotsSupported(boolean backgroundSnapshotsSupported) {
        this.backgroundSnapshotsSupported = backgroundSnapshotsSupported;
    }

    public boolean isBackgroundSnapshotsSupported() {
        return backgroundSnapshotsSupported;
    }

    public boolean getPreAssignedPCIUnitNumbersSupported() {
        return preAssignedPCIUnitNumbersSupported;
    }

    public void setPreAssignedPCIUnitNumbersSupported(boolean preAssignedPCIUnitNumbersSupported) {
        this.preAssignedPCIUnitNumbersSupported = preAssignedPCIUnitNumbersSupported;
    }

    public boolean isPreAssignedPCIUnitNumbersSupported() {
        return preAssignedPCIUnitNumbersSupported;
    }

    public boolean getScreenshotSupported() {
        return screenshotSupported;
    }

    public void setScreenshotSupported(boolean screenshotSupported) {
        this.screenshotSupported = screenshotSupported;
    }

    public boolean isScreenshotSupported() {
        return screenshotSupported;
    }

    public boolean getScaledScreenshotSupported() {
        return scaledScreenshotSupported;
    }

    public void setScaledScreenshotSupported(boolean scaledScreenshotSupported) {
        this.scaledScreenshotSupported = scaledScreenshotSupported;
    }

    public boolean isScaledScreenshotSupported() {
        return scaledScreenshotSupported;
    }

    public Boolean getStorageVMotionSupported() {
        return storageVMotionSupported;
    }

    public void setStorageVMotionSupported(Boolean storageVMotionSupported) {
        this.storageVMotionSupported = storageVMotionSupported;
    }

    public Boolean isStorageVMotionSupported() {
        return storageVMotionSupported;
    }

    public Boolean getVmotionWithStorageVMotionSupported() {
        return vmotionWithStorageVMotionSupported;
    }

    public void setVmotionWithStorageVMotionSupported(Boolean vmotionWithStorageVMotionSupported) {
        this.vmotionWithStorageVMotionSupported = vmotionWithStorageVMotionSupported;
    }

    public Boolean isVmotionWithStorageVMotionSupported() {
        return vmotionWithStorageVMotionSupported;
    }

    public Boolean getVmotionAcrossNetworkSupported() {
        return vmotionAcrossNetworkSupported;
    }

    public void setVmotionAcrossNetworkSupported(Boolean vmotionAcrossNetworkSupported) {
        this.vmotionAcrossNetworkSupported = vmotionAcrossNetworkSupported;
    }

    public Boolean isVmotionAcrossNetworkSupported() {
        return vmotionAcrossNetworkSupported;
    }

    public Integer getMaxNumDisksSVMotion() {
        return maxNumDisksSVMotion;
    }

    public void setMaxNumDisksSVMotion(Integer maxNumDisksSVMotion) {
        this.maxNumDisksSVMotion = maxNumDisksSVMotion;
    }

    public Boolean getHbrNicSelectionSupported() {
        return hbrNicSelectionSupported;
    }

    public void setHbrNicSelectionSupported(Boolean hbrNicSelectionSupported) {
        this.hbrNicSelectionSupported = hbrNicSelectionSupported;
    }

    public Boolean isHbrNicSelectionSupported() {
        return hbrNicSelectionSupported;
    }

    public Boolean getVrNfcNicSelectionSupported() {
        return vrNfcNicSelectionSupported;
    }

    public void setVrNfcNicSelectionSupported(Boolean vrNfcNicSelectionSupported) {
        this.vrNfcNicSelectionSupported = vrNfcNicSelectionSupported;
    }

    public Boolean isVrNfcNicSelectionSupported() {
        return vrNfcNicSelectionSupported;
    }

    public Boolean getRecordReplaySupported() {
        return recordReplaySupported;
    }

    public void setRecordReplaySupported(Boolean recordReplaySupported) {
        this.recordReplaySupported = recordReplaySupported;
    }

    public Boolean isRecordReplaySupported() {
        return recordReplaySupported;
    }

    public Boolean getFtSupported() {
        return ftSupported;
    }

    public void setFtSupported(Boolean ftSupported) {
        this.ftSupported = ftSupported;
    }

    public Boolean isFtSupported() {
        return ftSupported;
    }

    public String getReplayUnsupportedReason() {
        return replayUnsupportedReason;
    }

    public void setReplayUnsupportedReason(String replayUnsupportedReason) {
        this.replayUnsupportedReason = replayUnsupportedReason;
    }

    public String[] getReplayCompatibilityIssues() {
        if ((replayCompatibilityIssues) == null) {
            return (NULL_REPLAY_COMPATIBILITY_ISSUES_ARRAY);
        }
        return replayCompatibilityIssues;
    }

    public void setReplayCompatibilityIssues(String[] replayCompatibilityIssues) {
        this.replayCompatibilityIssues = replayCompatibilityIssues;
    }

    public Boolean getSmpFtSupported() {
        return smpFtSupported;
    }

    public void setSmpFtSupported(Boolean smpFtSupported) {
        this.smpFtSupported = smpFtSupported;
    }

    public Boolean isSmpFtSupported() {
        return smpFtSupported;
    }

    public String[] getFtCompatibilityIssues() {
        if ((ftCompatibilityIssues) == null) {
            return (NULL_FT_COMPATIBILITY_ISSUES_ARRAY);
        }
        return ftCompatibilityIssues;
    }

    public void setFtCompatibilityIssues(String[] ftCompatibilityIssues) {
        this.ftCompatibilityIssues = ftCompatibilityIssues;
    }

    public String[] getSmpFtCompatibilityIssues() {
        if ((smpFtCompatibilityIssues) == null) {
            return (NULL_SMP_FT_COMPATIBILITY_ISSUES_ARRAY);
        }
        return smpFtCompatibilityIssues;
    }

    public void setSmpFtCompatibilityIssues(String[] smpFtCompatibilityIssues) {
        this.smpFtCompatibilityIssues = smpFtCompatibilityIssues;
    }

    public Integer getMaxVcpusPerFtVm() {
        return maxVcpusPerFtVm;
    }

    public void setMaxVcpusPerFtVm(Integer maxVcpusPerFtVm) {
        this.maxVcpusPerFtVm = maxVcpusPerFtVm;
    }

    public Boolean getLoginBySSLThumbprintSupported() {
        return loginBySSLThumbprintSupported;
    }

    public void setLoginBySSLThumbprintSupported(Boolean loginBySSLThumbprintSupported) {
        this.loginBySSLThumbprintSupported = loginBySSLThumbprintSupported;
    }

    public Boolean isLoginBySSLThumbprintSupported() {
        return loginBySSLThumbprintSupported;
    }

    public Boolean getCloneFromSnapshotSupported() {
        return cloneFromSnapshotSupported;
    }

    public void setCloneFromSnapshotSupported(Boolean cloneFromSnapshotSupported) {
        this.cloneFromSnapshotSupported = cloneFromSnapshotSupported;
    }

    public Boolean isCloneFromSnapshotSupported() {
        return cloneFromSnapshotSupported;
    }

    public Boolean getDeltaDiskBackingsSupported() {
        return deltaDiskBackingsSupported;
    }

    public void setDeltaDiskBackingsSupported(Boolean deltaDiskBackingsSupported) {
        this.deltaDiskBackingsSupported = deltaDiskBackingsSupported;
    }

    public Boolean isDeltaDiskBackingsSupported() {
        return deltaDiskBackingsSupported;
    }

    public Boolean getPerVMNetworkTrafficShapingSupported() {
        return perVMNetworkTrafficShapingSupported;
    }

    public void setPerVMNetworkTrafficShapingSupported(Boolean perVMNetworkTrafficShapingSupported) {
        this.perVMNetworkTrafficShapingSupported = perVMNetworkTrafficShapingSupported;
    }

    public Boolean isPerVMNetworkTrafficShapingSupported() {
        return perVMNetworkTrafficShapingSupported;
    }

    public Boolean getTpmSupported() {
        return tpmSupported;
    }

    public void setTpmSupported(Boolean tpmSupported) {
        this.tpmSupported = tpmSupported;
    }

    public Boolean isTpmSupported() {
        return tpmSupported;
    }

    public String getTpmVersion() {
        return tpmVersion;
    }

    public void setTpmVersion(String tpmVersion) {
        this.tpmVersion = tpmVersion;
    }

    public Boolean getTxtEnabled() {
        return txtEnabled;
    }

    public void setTxtEnabled(Boolean txtEnabled) {
        this.txtEnabled = txtEnabled;
    }

    public Boolean isTxtEnabled() {
        return txtEnabled;
    }

    public HostCpuIdInfo[] getSupportedCpuFeature() {
        if ((supportedCpuFeature) == null) {
            return (NULL_SUPPORTED_CPU_FEATURE_ARRAY);
        }
        return supportedCpuFeature;
    }

    public void setSupportedCpuFeature(HostCpuIdInfo[] supportedCpuFeature) {
        this.supportedCpuFeature = supportedCpuFeature;
    }

    public Boolean getVirtualExecUsageSupported() {
        return virtualExecUsageSupported;
    }

    public void setVirtualExecUsageSupported(Boolean virtualExecUsageSupported) {
        this.virtualExecUsageSupported = virtualExecUsageSupported;
    }

    public Boolean isVirtualExecUsageSupported() {
        return virtualExecUsageSupported;
    }

    public Boolean getStorageIORMSupported() {
        return storageIORMSupported;
    }

    public void setStorageIORMSupported(Boolean storageIORMSupported) {
        this.storageIORMSupported = storageIORMSupported;
    }

    public Boolean isStorageIORMSupported() {
        return storageIORMSupported;
    }

    public Boolean getVmDirectPathGen2Supported() {
        return vmDirectPathGen2Supported;
    }

    public void setVmDirectPathGen2Supported(Boolean vmDirectPathGen2Supported) {
        this.vmDirectPathGen2Supported = vmDirectPathGen2Supported;
    }

    public Boolean isVmDirectPathGen2Supported() {
        return vmDirectPathGen2Supported;
    }

    public String[] getVmDirectPathGen2UnsupportedReason() {
        if ((vmDirectPathGen2UnsupportedReason) == null) {
            return (NULL_VM_DIRECT_PATH_GEN2_UNSUPPORTED_REASON_ARRAY);
        }
        return vmDirectPathGen2UnsupportedReason;
    }

    public void setVmDirectPathGen2UnsupportedReason(String[] vmDirectPathGen2UnsupportedReason) {
        this.vmDirectPathGen2UnsupportedReason = vmDirectPathGen2UnsupportedReason;
    }

    public String getVmDirectPathGen2UnsupportedReasonExtended() {
        return vmDirectPathGen2UnsupportedReasonExtended;
    }

    public void setVmDirectPathGen2UnsupportedReasonExtended(String vmDirectPathGen2UnsupportedReasonExtended) {
        this.vmDirectPathGen2UnsupportedReasonExtended = vmDirectPathGen2UnsupportedReasonExtended;
    }

    public int[] getSupportedVmfsMajorVersion() {
        if ((supportedVmfsMajorVersion) == null) {
            return (NULL_SUPPORTED_VMFS_MAJOR_VERSION_ARRAY);
        }
        return supportedVmfsMajorVersion;
    }

    public void setSupportedVmfsMajorVersion(int[] supportedVmfsMajorVersion) {
        this.supportedVmfsMajorVersion = supportedVmfsMajorVersion;
    }

    public Boolean getVStorageCapable() {
        return vStorageCapable;
    }

    public void setVStorageCapable(Boolean vStorageCapable) {
        this.vStorageCapable = vStorageCapable;
    }

    public Boolean isVStorageCapable() {
        return vStorageCapable;
    }

    public Boolean getSnapshotRelayoutSupported() {
        return snapshotRelayoutSupported;
    }

    public void setSnapshotRelayoutSupported(Boolean snapshotRelayoutSupported) {
        this.snapshotRelayoutSupported = snapshotRelayoutSupported;
    }

    public Boolean isSnapshotRelayoutSupported() {
        return snapshotRelayoutSupported;
    }

    public Boolean getFirewallIpRulesSupported() {
        return firewallIpRulesSupported;
    }

    public void setFirewallIpRulesSupported(Boolean firewallIpRulesSupported) {
        this.firewallIpRulesSupported = firewallIpRulesSupported;
    }

    public Boolean isFirewallIpRulesSupported() {
        return firewallIpRulesSupported;
    }

    public Boolean getServicePackageInfoSupported() {
        return servicePackageInfoSupported;
    }

    public void setServicePackageInfoSupported(Boolean servicePackageInfoSupported) {
        this.servicePackageInfoSupported = servicePackageInfoSupported;
    }

    public Boolean isServicePackageInfoSupported() {
        return servicePackageInfoSupported;
    }

    public Integer getMaxHostRunningVms() {
        return maxHostRunningVms;
    }

    public void setMaxHostRunningVms(Integer maxHostRunningVms) {
        this.maxHostRunningVms = maxHostRunningVms;
    }

    public Integer getMaxHostSupportedVcpus() {
        return maxHostSupportedVcpus;
    }

    public void setMaxHostSupportedVcpus(Integer maxHostSupportedVcpus) {
        this.maxHostSupportedVcpus = maxHostSupportedVcpus;
    }

    public Boolean getVmfsDatastoreMountCapable() {
        return vmfsDatastoreMountCapable;
    }

    public void setVmfsDatastoreMountCapable(Boolean vmfsDatastoreMountCapable) {
        this.vmfsDatastoreMountCapable = vmfsDatastoreMountCapable;
    }

    public Boolean isVmfsDatastoreMountCapable() {
        return vmfsDatastoreMountCapable;
    }

    public Boolean getEightPlusHostVmfsSharedAccessSupported() {
        return eightPlusHostVmfsSharedAccessSupported;
    }

    public void setEightPlusHostVmfsSharedAccessSupported(Boolean eightPlusHostVmfsSharedAccessSupported) {
        this.eightPlusHostVmfsSharedAccessSupported = eightPlusHostVmfsSharedAccessSupported;
    }

    public Boolean isEightPlusHostVmfsSharedAccessSupported() {
        return eightPlusHostVmfsSharedAccessSupported;
    }

    public Boolean getNestedHVSupported() {
        return nestedHVSupported;
    }

    public void setNestedHVSupported(Boolean nestedHVSupported) {
        this.nestedHVSupported = nestedHVSupported;
    }

    public Boolean isNestedHVSupported() {
        return nestedHVSupported;
    }

    public Boolean getVpmcSupported() {
        return vPMCSupported;
    }

    public void setVpmcSupported(Boolean vPMCSupported) {
        this.vPMCSupported = vPMCSupported;
    }

    public Boolean isVpmcSupported() {
        return vPMCSupported;
    }

    public Boolean getInterVMCommunicationThroughVMCISupported() {
        return interVMCommunicationThroughVMCISupported;
    }

    public void setInterVMCommunicationThroughVMCISupported(Boolean interVMCommunicationThroughVMCISupported) {
        this.interVMCommunicationThroughVMCISupported = interVMCommunicationThroughVMCISupported;
    }

    public Boolean isInterVMCommunicationThroughVMCISupported() {
        return interVMCommunicationThroughVMCISupported;
    }

    public Boolean getScheduledHardwareUpgradeSupported() {
        return scheduledHardwareUpgradeSupported;
    }

    public void setScheduledHardwareUpgradeSupported(Boolean scheduledHardwareUpgradeSupported) {
        this.scheduledHardwareUpgradeSupported = scheduledHardwareUpgradeSupported;
    }

    public Boolean isScheduledHardwareUpgradeSupported() {
        return scheduledHardwareUpgradeSupported;
    }

    public Boolean getFeatureCapabilitiesSupported() {
        return featureCapabilitiesSupported;
    }

    public void setFeatureCapabilitiesSupported(Boolean featureCapabilitiesSupported) {
        this.featureCapabilitiesSupported = featureCapabilitiesSupported;
    }

    public Boolean isFeatureCapabilitiesSupported() {
        return featureCapabilitiesSupported;
    }

    public Boolean getLatencySensitivitySupported() {
        return latencySensitivitySupported;
    }

    public void setLatencySensitivitySupported(Boolean latencySensitivitySupported) {
        this.latencySensitivitySupported = latencySensitivitySupported;
    }

    public Boolean isLatencySensitivitySupported() {
        return latencySensitivitySupported;
    }

    public Boolean getStoragePolicySupported() {
        return storagePolicySupported;
    }

    public void setStoragePolicySupported(Boolean storagePolicySupported) {
        this.storagePolicySupported = storagePolicySupported;
    }

    public Boolean isStoragePolicySupported() {
        return storagePolicySupported;
    }

    public Boolean getAccel3DSupported() {
        return accel3dSupported;
    }

    public void setAccel3DSupported(Boolean accel3dSupported) {
        this.accel3dSupported = accel3dSupported;
    }

    public Boolean isAccel3DSupported() {
        return accel3dSupported;
    }

    public Boolean getReliableMemoryAware() {
        return reliableMemoryAware;
    }

    public void setReliableMemoryAware(Boolean reliableMemoryAware) {
        this.reliableMemoryAware = reliableMemoryAware;
    }

    public Boolean isReliableMemoryAware() {
        return reliableMemoryAware;
    }

    public Boolean getMultipleNetworkStackInstanceSupported() {
        return multipleNetworkStackInstanceSupported;
    }

    public void setMultipleNetworkStackInstanceSupported(Boolean multipleNetworkStackInstanceSupported) {
        this.multipleNetworkStackInstanceSupported = multipleNetworkStackInstanceSupported;
    }

    public Boolean isMultipleNetworkStackInstanceSupported() {
        return multipleNetworkStackInstanceSupported;
    }

    public Boolean getMessageBusProxySupported() {
        return messageBusProxySupported;
    }

    public void setMessageBusProxySupported(Boolean messageBusProxySupported) {
        this.messageBusProxySupported = messageBusProxySupported;
    }

    public Boolean isMessageBusProxySupported() {
        return messageBusProxySupported;
    }

    public Boolean getVsanSupported() {
        return vsanSupported;
    }

    public void setVsanSupported(Boolean vsanSupported) {
        this.vsanSupported = vsanSupported;
    }

    public Boolean isVsanSupported() {
        return vsanSupported;
    }

    public Boolean getVFlashSupported() {
        return vFlashSupported;
    }

    public void setVFlashSupported(Boolean vFlashSupported) {
        this.vFlashSupported = vFlashSupported;
    }

    public Boolean isVFlashSupported() {
        return vFlashSupported;
    }

    public Boolean getHostAccessManagerSupported() {
        return hostAccessManagerSupported;
    }

    public void setHostAccessManagerSupported(Boolean hostAccessManagerSupported) {
        this.hostAccessManagerSupported = hostAccessManagerSupported;
    }

    public Boolean isHostAccessManagerSupported() {
        return hostAccessManagerSupported;
    }

    public Boolean getProvisioningNicSelectionSupported() {
        return provisioningNicSelectionSupported;
    }

    public void setProvisioningNicSelectionSupported(Boolean provisioningNicSelectionSupported) {
        this.provisioningNicSelectionSupported = provisioningNicSelectionSupported;
    }

    public Boolean isProvisioningNicSelectionSupported() {
        return provisioningNicSelectionSupported;
    }

    public Boolean getNfs41Supported() {
        return nfs41Supported;
    }

    public void setNfs41Supported(Boolean nfs41Supported) {
        this.nfs41Supported = nfs41Supported;
    }

    public Boolean isNfs41Supported() {
        return nfs41Supported;
    }

    public Boolean getNfs41Krb5ISupported() {
        return nfs41Krb5iSupported;
    }

    public void setNfs41Krb5ISupported(Boolean nfs41Krb5iSupported) {
        this.nfs41Krb5iSupported = nfs41Krb5iSupported;
    }

    public Boolean isNfs41Krb5ISupported() {
        return nfs41Krb5iSupported;
    }

    public Boolean getTurnDiskLocatorLedSupported() {
        return turnDiskLocatorLedSupported;
    }

    public void setTurnDiskLocatorLedSupported(Boolean turnDiskLocatorLedSupported) {
        this.turnDiskLocatorLedSupported = turnDiskLocatorLedSupported;
    }

    public Boolean isTurnDiskLocatorLedSupported() {
        return turnDiskLocatorLedSupported;
    }

    public Boolean getVirtualVolumeDatastoreSupported() {
        return virtualVolumeDatastoreSupported;
    }

    public void setVirtualVolumeDatastoreSupported(Boolean virtualVolumeDatastoreSupported) {
        this.virtualVolumeDatastoreSupported = virtualVolumeDatastoreSupported;
    }

    public Boolean isVirtualVolumeDatastoreSupported() {
        return virtualVolumeDatastoreSupported;
    }

    public Boolean getMarkAsSsdSupported() {
        return markAsSsdSupported;
    }

    public void setMarkAsSsdSupported(Boolean markAsSsdSupported) {
        this.markAsSsdSupported = markAsSsdSupported;
    }

    public Boolean isMarkAsSsdSupported() {
        return markAsSsdSupported;
    }

    public Boolean getMarkAsLocalSupported() {
        return markAsLocalSupported;
    }

    public void setMarkAsLocalSupported(Boolean markAsLocalSupported) {
        this.markAsLocalSupported = markAsLocalSupported;
    }

    public Boolean isMarkAsLocalSupported() {
        return markAsLocalSupported;
    }

    public Boolean getSmartCardAuthenticationSupported() {
        return smartCardAuthenticationSupported;
    }

    public void setSmartCardAuthenticationSupported(Boolean smartCardAuthenticationSupported) {
        this.smartCardAuthenticationSupported = smartCardAuthenticationSupported;
    }

    public Boolean isSmartCardAuthenticationSupported() {
        return smartCardAuthenticationSupported;
    }

    public Boolean getPMemSupported() {
        return pMemSupported;
    }

    public void setPMemSupported(Boolean pMemSupported) {
        this.pMemSupported = pMemSupported;
    }

    public Boolean isPMemSupported() {
        return pMemSupported;
    }

    public Boolean getPMemSnapshotSupported() {
        return pMemSnapshotSupported;
    }

    public void setPMemSnapshotSupported(Boolean pMemSnapshotSupported) {
        this.pMemSnapshotSupported = pMemSnapshotSupported;
    }

    public Boolean isPMemSnapshotSupported() {
        return pMemSnapshotSupported;
    }

    public Boolean getCryptoSupported() {
        return cryptoSupported;
    }

    public void setCryptoSupported(Boolean cryptoSupported) {
        this.cryptoSupported = cryptoSupported;
    }

    public Boolean isCryptoSupported() {
        return cryptoSupported;
    }

    public Boolean getOneKVolumeAPIsSupported() {
        return oneKVolumeAPIsSupported;
    }

    public void setOneKVolumeAPIsSupported(Boolean oneKVolumeAPIsSupported) {
        this.oneKVolumeAPIsSupported = oneKVolumeAPIsSupported;
    }

    public Boolean isOneKVolumeAPIsSupported() {
        return oneKVolumeAPIsSupported;
    }

    public Boolean getGatewayOnNicSupported() {
        return gatewayOnNicSupported;
    }

    public void setGatewayOnNicSupported(Boolean gatewayOnNicSupported) {
        this.gatewayOnNicSupported = gatewayOnNicSupported;
    }

    public Boolean isGatewayOnNicSupported() {
        return gatewayOnNicSupported;
    }

    public Boolean getUpitSupported() {
        return upitSupported;
    }

    public void setUpitSupported(Boolean upitSupported) {
        this.upitSupported = upitSupported;
    }

    public Boolean isUpitSupported() {
        return upitSupported;
    }

    public Boolean getCpuHwMmuSupported() {
        return cpuHwMmuSupported;
    }

    public void setCpuHwMmuSupported(Boolean cpuHwMmuSupported) {
        this.cpuHwMmuSupported = cpuHwMmuSupported;
    }

    public Boolean isCpuHwMmuSupported() {
        return cpuHwMmuSupported;
    }

    public Boolean getEncryptedVMotionSupported() {
        return encryptedVMotionSupported;
    }

    public void setEncryptedVMotionSupported(Boolean encryptedVMotionSupported) {
        this.encryptedVMotionSupported = encryptedVMotionSupported;
    }

    public Boolean isEncryptedVMotionSupported() {
        return encryptedVMotionSupported;
    }

    public Boolean getEncryptionChangeOnAddRemoveSupported() {
        return encryptionChangeOnAddRemoveSupported;
    }

    public void setEncryptionChangeOnAddRemoveSupported(Boolean encryptionChangeOnAddRemoveSupported) {
        this.encryptionChangeOnAddRemoveSupported = encryptionChangeOnAddRemoveSupported;
    }

    public Boolean isEncryptionChangeOnAddRemoveSupported() {
        return encryptionChangeOnAddRemoveSupported;
    }

    public Boolean getEncryptionHotOperationSupported() {
        return encryptionHotOperationSupported;
    }

    public void setEncryptionHotOperationSupported(Boolean encryptionHotOperationSupported) {
        this.encryptionHotOperationSupported = encryptionHotOperationSupported;
    }

    public Boolean isEncryptionHotOperationSupported() {
        return encryptionHotOperationSupported;
    }

    public Boolean getEncryptionWithSnapshotsSupported() {
        return encryptionWithSnapshotsSupported;
    }

    public void setEncryptionWithSnapshotsSupported(Boolean encryptionWithSnapshotsSupported) {
        this.encryptionWithSnapshotsSupported = encryptionWithSnapshotsSupported;
    }

    public Boolean isEncryptionWithSnapshotsSupported() {
        return encryptionWithSnapshotsSupported;
    }

    public Boolean getEncryptionFaultToleranceSupported() {
        return encryptionFaultToleranceSupported;
    }

    public void setEncryptionFaultToleranceSupported(Boolean encryptionFaultToleranceSupported) {
        this.encryptionFaultToleranceSupported = encryptionFaultToleranceSupported;
    }

    public Boolean isEncryptionFaultToleranceSupported() {
        return encryptionFaultToleranceSupported;
    }

    public Boolean getEncryptionMemorySaveSupported() {
        return encryptionMemorySaveSupported;
    }

    public void setEncryptionMemorySaveSupported(Boolean encryptionMemorySaveSupported) {
        this.encryptionMemorySaveSupported = encryptionMemorySaveSupported;
    }

    public Boolean isEncryptionMemorySaveSupported() {
        return encryptionMemorySaveSupported;
    }

    public Boolean getEncryptionRDMSupported() {
        return encryptionRDMSupported;
    }

    public void setEncryptionRDMSupported(Boolean encryptionRDMSupported) {
        this.encryptionRDMSupported = encryptionRDMSupported;
    }

    public Boolean isEncryptionRDMSupported() {
        return encryptionRDMSupported;
    }

    public Boolean getEncryptionVFlashSupported() {
        return encryptionVFlashSupported;
    }

    public void setEncryptionVFlashSupported(Boolean encryptionVFlashSupported) {
        this.encryptionVFlashSupported = encryptionVFlashSupported;
    }

    public Boolean isEncryptionVFlashSupported() {
        return encryptionVFlashSupported;
    }

    public Boolean getEncryptionCBRCSupported() {
        return encryptionCBRCSupported;
    }

    public void setEncryptionCBRCSupported(Boolean encryptionCBRCSupported) {
        this.encryptionCBRCSupported = encryptionCBRCSupported;
    }

    public Boolean isEncryptionCBRCSupported() {
        return encryptionCBRCSupported;
    }

    public Boolean getEncryptionHBRSupported() {
        return encryptionHBRSupported;
    }

    public void setEncryptionHBRSupported(Boolean encryptionHBRSupported) {
        this.encryptionHBRSupported = encryptionHBRSupported;
    }

    public Boolean isEncryptionHBRSupported() {
        return encryptionHBRSupported;
    }

    public Boolean getFtEfiSupported() {
        return ftEfiSupported;
    }

    public void setFtEfiSupported(Boolean ftEfiSupported) {
        this.ftEfiSupported = ftEfiSupported;
    }

    public Boolean isFtEfiSupported() {
        return ftEfiSupported;
    }

    public String getUnmapMethodSupported() {
        return unmapMethodSupported;
    }

    public void setUnmapMethodSupported(String unmapMethodSupported) {
        this.unmapMethodSupported = unmapMethodSupported;
    }

    public Integer getMaxMemMBPerFtVm() {
        return maxMemMBPerFtVm;
    }

    public void setMaxMemMBPerFtVm(Integer maxMemMBPerFtVm) {
        this.maxMemMBPerFtVm = maxMemMBPerFtVm;
    }

    public Boolean getVirtualMmuUsageIgnored() {
        return virtualMmuUsageIgnored;
    }

    public void setVirtualMmuUsageIgnored(Boolean virtualMmuUsageIgnored) {
        this.virtualMmuUsageIgnored = virtualMmuUsageIgnored;
    }

    public Boolean isVirtualMmuUsageIgnored() {
        return virtualMmuUsageIgnored;
    }

    public Boolean getVirtualExecUsageIgnored() {
        return virtualExecUsageIgnored;
    }

    public void setVirtualExecUsageIgnored(Boolean virtualExecUsageIgnored) {
        this.virtualExecUsageIgnored = virtualExecUsageIgnored;
    }

    public Boolean isVirtualExecUsageIgnored() {
        return virtualExecUsageIgnored;
    }

    public Boolean getVmCreateDateSupported() {
        return vmCreateDateSupported;
    }

    public void setVmCreateDateSupported(Boolean vmCreateDateSupported) {
        this.vmCreateDateSupported = vmCreateDateSupported;
    }

    public Boolean isVmCreateDateSupported() {
        return vmCreateDateSupported;
    }

    public Boolean getVmfs3EOLSupported() {
        return vmfs3EOLSupported;
    }

    public void setVmfs3EOLSupported(Boolean vmfs3EOLSupported) {
        this.vmfs3EOLSupported = vmfs3EOLSupported;
    }

    public Boolean isVmfs3EOLSupported() {
        return vmfs3EOLSupported;
    }

    public Boolean getFtVmcpSupported() {
        return ftVmcpSupported;
    }

    public void setFtVmcpSupported(Boolean ftVmcpSupported) {
        this.ftVmcpSupported = ftVmcpSupported;
    }

    public Boolean isFtVmcpSupported() {
        return ftVmcpSupported;
    }

}
