//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostPnicNetworkResourceInfo
    extends DynamicData
{

    public String pnicDevice;
    public Long availableBandwidthForVMTraffic;
    public Long unusedBandwidthForVMTraffic;
    private final static HostPlacedVirtualNicIdentifier[] NULL_PLACED_VIRTUAL_NICS_ARRAY = new HostPlacedVirtualNicIdentifier[ 0 ] ;
    public HostPlacedVirtualNicIdentifier[] placedVirtualNics;

    public String getPnicDevice() {
        return pnicDevice;
    }

    public void setPnicDevice(String pnicDevice) {
        this.pnicDevice = pnicDevice;
    }

    public Long getAvailableBandwidthForVMTraffic() {
        return availableBandwidthForVMTraffic;
    }

    public void setAvailableBandwidthForVMTraffic(Long availableBandwidthForVMTraffic) {
        this.availableBandwidthForVMTraffic = availableBandwidthForVMTraffic;
    }

    public Long getUnusedBandwidthForVMTraffic() {
        return unusedBandwidthForVMTraffic;
    }

    public void setUnusedBandwidthForVMTraffic(Long unusedBandwidthForVMTraffic) {
        this.unusedBandwidthForVMTraffic = unusedBandwidthForVMTraffic;
    }

    public HostPlacedVirtualNicIdentifier[] getPlacedVirtualNics() {
        if ((placedVirtualNics) == null) {
            return (NULL_PLACED_VIRTUAL_NICS_ARRAY);
        }
        return placedVirtualNics;
    }

    public void setPlacedVirtualNics(HostPlacedVirtualNicIdentifier[] placedVirtualNics) {
        this.placedVirtualNics = placedVirtualNics;
    }

}
