//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostNetworkTrafficShapingPolicy
    extends DynamicData
{

    public Boolean enabled;
    public Long averageBandwidth;
    public Long peakBandwidth;
    public Long burstSize;

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean isEnabled() {
        return enabled;
    }

    public Long getAverageBandwidth() {
        return averageBandwidth;
    }

    public void setAverageBandwidth(Long averageBandwidth) {
        this.averageBandwidth = averageBandwidth;
    }

    public Long getPeakBandwidth() {
        return peakBandwidth;
    }

    public void setPeakBandwidth(Long peakBandwidth) {
        this.peakBandwidth = peakBandwidth;
    }

    public Long getBurstSize() {
        return burstSize;
    }

    public void setBurstSize(Long burstSize) {
        this.burstSize = burstSize;
    }

}
