//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostProfileManagerConfigTaskList
    extends DynamicData
{

    public HostConfigSpec configSpec;
    private final static LocalizableMessage[] NULL_TASK_DESCRIPTION_ARRAY = new LocalizableMessage[ 0 ] ;
    public LocalizableMessage[] taskDescription;
    private final static String[] NULL_TASK_LIST_REQUIREMENT_ARRAY = new String[ 0 ] ;
    public String[] taskListRequirement;

    public HostConfigSpec getConfigSpec() {
        return configSpec;
    }

    public void setConfigSpec(HostConfigSpec configSpec) {
        this.configSpec = configSpec;
    }

    public LocalizableMessage[] getTaskDescription() {
        if ((taskDescription) == null) {
            return (NULL_TASK_DESCRIPTION_ARRAY);
        }
        return taskDescription;
    }

    public void setTaskDescription(LocalizableMessage[] taskDescription) {
        this.taskDescription = taskDescription;
    }

    public String[] getTaskListRequirement() {
        if ((taskListRequirement) == null) {
            return (NULL_TASK_LIST_REQUIREMENT_ARRAY);
        }
        return taskListRequirement;
    }

    public void setTaskListRequirement(String[] taskListRequirement) {
        this.taskListRequirement = taskListRequirement;
    }

}
