//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostFirewallRuleset
    extends DynamicData
{

    public String key;
    public String label;
    public boolean required;
    private final static HostFirewallRule[] NULL_RULE_ARRAY = new HostFirewallRule[ 0 ] ;
    public HostFirewallRule[] rule;
    public String service;
    public boolean enabled;
    public HostFirewallRulesetIpList allowedHosts;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public boolean getRequired() {
        return required;
    }

    public void setRequired(boolean required) {
        this.required = required;
    }

    public boolean isRequired() {
        return required;
    }

    public HostFirewallRule[] getRule() {
        if ((rule) == null) {
            return (NULL_RULE_ARRAY);
        }
        return rule;
    }

    public void setRule(HostFirewallRule[] rule) {
        this.rule = rule;
    }

    public String getService() {
        return service;
    }

    public void setService(String service) {
        this.service = service;
    }

    public boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public HostFirewallRulesetIpList getAllowedHosts() {
        return allowedHosts;
    }

    public void setAllowedHosts(HostFirewallRulesetIpList allowedHosts) {
        this.allowedHosts = allowedHosts;
    }

}
