//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostDnsConfigSpec
    extends HostDnsConfig
{

    public HostVirtualNicConnection virtualNicConnection;
    public HostVirtualNicConnection virtualNicConnectionV6;

    public HostVirtualNicConnection getVirtualNicConnection() {
        return virtualNicConnection;
    }

    public void setVirtualNicConnection(HostVirtualNicConnection virtualNicConnection) {
        this.virtualNicConnection = virtualNicConnection;
    }

    public HostVirtualNicConnection getVirtualNicConnectionV6() {
        return virtualNicConnectionV6;
    }

    public void setVirtualNicConnectionV6(HostVirtualNicConnection virtualNicConnectionV6) {
        this.virtualNicConnectionV6 = virtualNicConnectionV6;
    }

}
