//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostFlagInfo
    extends DynamicData
{

    public Boolean backgroundSnapshotsEnabled;

    public Boolean getBackgroundSnapshotsEnabled() {
        return backgroundSnapshotsEnabled;
    }

    public void setBackgroundSnapshotsEnabled(Boolean backgroundSnapshotsEnabled) {
        this.backgroundSnapshotsEnabled = backgroundSnapshotsEnabled;
    }

    public Boolean isBackgroundSnapshotsEnabled() {
        return backgroundSnapshotsEnabled;
    }

}
