//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostVirtualSwitch
    extends DynamicData
{

    public String name;
    public String key;
    public int numPorts;
    public int numPortsAvailable;
    public Integer mtu;
    private final static String[] NULL_PORTGROUP_ARRAY = new String[ 0 ] ;
    public String[] portgroup;
    private final static String[] NULL_PNIC_ARRAY = new String[ 0 ] ;
    public String[] pnic;
    public HostVirtualSwitchSpec spec;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public int getNumPorts() {
        return numPorts;
    }

    public void setNumPorts(int numPorts) {
        this.numPorts = numPorts;
    }

    public int getNumPortsAvailable() {
        return numPortsAvailable;
    }

    public void setNumPortsAvailable(int numPortsAvailable) {
        this.numPortsAvailable = numPortsAvailable;
    }

    public Integer getMtu() {
        return mtu;
    }

    public void setMtu(Integer mtu) {
        this.mtu = mtu;
    }

    public String[] getPortgroup() {
        if ((portgroup) == null) {
            return (NULL_PORTGROUP_ARRAY);
        }
        return portgroup;
    }

    public void setPortgroup(String[] portgroup) {
        this.portgroup = portgroup;
    }

    public String[] getPnic() {
        if ((pnic) == null) {
            return (NULL_PNIC_ARRAY);
        }
        return pnic;
    }

    public void setPnic(String[] pnic) {
        this.pnic = pnic;
    }

    public HostVirtualSwitchSpec getSpec() {
        return spec;
    }

    public void setSpec(HostVirtualSwitchSpec spec) {
        this.spec = spec;
    }

}
