//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostSslThumbprintInfo
    extends DynamicData
{

    public String principal;
    public String ownerTag;
    private final static String[] NULL_SSL_THUMBPRINTS_ARRAY = new String[ 0 ] ;
    public String[] sslThumbprints;

    public String getPrincipal() {
        return principal;
    }

    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    public String getOwnerTag() {
        return ownerTag;
    }

    public void setOwnerTag(String ownerTag) {
        this.ownerTag = ownerTag;
    }

    public String[] getSslThumbprints() {
        if ((sslThumbprints) == null) {
            return (NULL_SSL_THUMBPRINTS_ARRAY);
        }
        return sslThumbprints;
    }

    public void setSslThumbprints(String[] sslThumbprints) {
        this.sslThumbprints = sslThumbprints;
    }

}
