//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostIpmiInfo
    extends DynamicData
{

    public String bmcIpAddress;
    public String bmcMacAddress;
    public String login;
    public String password;

    public String getBmcIpAddress() {
        return bmcIpAddress;
    }

    public void setBmcIpAddress(String bmcIpAddress) {
        this.bmcIpAddress = bmcIpAddress;
    }

    public String getBmcMacAddress() {
        return bmcMacAddress;
    }

    public void setBmcMacAddress(String bmcMacAddress) {
        this.bmcMacAddress = bmcMacAddress;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
