//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostNetworkConfigResult
    extends DynamicData
{

    private final static String[] NULL_VNIC_DEVICE_ARRAY = new String[ 0 ] ;
    public String[] vnicDevice;
    private final static String[] NULL_CONSOLE_VNIC_DEVICE_ARRAY = new String[ 0 ] ;
    public String[] consoleVnicDevice;

    public String[] getVnicDevice() {
        if ((vnicDevice) == null) {
            return (NULL_VNIC_DEVICE_ARRAY);
        }
        return vnicDevice;
    }

    public void setVnicDevice(String[] vnicDevice) {
        this.vnicDevice = vnicDevice;
    }

    public String[] getConsoleVnicDevice() {
        if ((consoleVnicDevice) == null) {
            return (NULL_CONSOLE_VNIC_DEVICE_ARRAY);
        }
        return consoleVnicDevice;
    }

    public void setConsoleVnicDevice(String[] consoleVnicDevice) {
        this.consoleVnicDevice = consoleVnicDevice;
    }

}
