//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostBootDeviceInfo
    extends DynamicData
{

    private final static HostBootDevice[] NULL_BOOT_DEVICES_ARRAY = new HostBootDevice[ 0 ] ;
    public HostBootDevice[] bootDevices;
    public String currentBootDeviceKey;

    public HostBootDevice[] getBootDevices() {
        if ((bootDevices) == null) {
            return (NULL_BOOT_DEVICES_ARRAY);
        }
        return bootDevices;
    }

    public void setBootDevices(HostBootDevice[] bootDevices) {
        this.bootDevices = bootDevices;
    }

    public String getCurrentBootDeviceKey() {
        return currentBootDeviceKey;
    }

    public void setCurrentBootDeviceKey(String currentBootDeviceKey) {
        this.currentBootDeviceKey = currentBootDeviceKey;
    }

}
