//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostAutoStartManagerConfig
    extends DynamicData
{

    public AutoStartDefaults defaults;
    private final static AutoStartPowerInfo[] NULL_POWER_INFO_ARRAY = new AutoStartPowerInfo[ 0 ] ;
    public AutoStartPowerInfo[] powerInfo;

    public AutoStartDefaults getDefaults() {
        return defaults;
    }

    public void setDefaults(AutoStartDefaults defaults) {
        this.defaults = defaults;
    }

    public AutoStartPowerInfo[] getPowerInfo() {
        if ((powerInfo) == null) {
            return (NULL_POWER_INFO_ARRAY);
        }
        return powerInfo;
    }

    public void setPowerInfo(AutoStartPowerInfo[] powerInfo) {
        this.powerInfo = powerInfo;
    }

}
