//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostSnmpConfigSpec
    extends DynamicData
{

    public Boolean enabled;
    public Integer port;
    private final static String[] NULL_READ_ONLY_COMMUNITIES_ARRAY = new String[ 0 ] ;
    public String[] readOnlyCommunities;
    private final static HostSnmpDestination[] NULL_TRAP_TARGETS_ARRAY = new HostSnmpDestination[ 0 ] ;
    public HostSnmpDestination[] trapTargets;
    private final static KeyValue[] NULL_OPTION_ARRAY = new KeyValue[ 0 ] ;
    public KeyValue[] option;

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean isEnabled() {
        return enabled;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String[] getReadOnlyCommunities() {
        if ((readOnlyCommunities) == null) {
            return (NULL_READ_ONLY_COMMUNITIES_ARRAY);
        }
        return readOnlyCommunities;
    }

    public void setReadOnlyCommunities(String[] readOnlyCommunities) {
        this.readOnlyCommunities = readOnlyCommunities;
    }

    public HostSnmpDestination[] getTrapTargets() {
        if ((trapTargets) == null) {
            return (NULL_TRAP_TARGETS_ARRAY);
        }
        return trapTargets;
    }

    public void setTrapTargets(HostSnmpDestination[] trapTargets) {
        this.trapTargets = trapTargets;
    }

    public KeyValue[] getOption() {
        if ((option) == null) {
            return (NULL_OPTION_ARRAY);
        }
        return option;
    }

    public void setOption(KeyValue[] option) {
        this.option = option;
    }

}
