//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostVmfsVolume
    extends HostFileSystemVolume
{

    public int blockSizeMb;
    public Integer blockSize;
    public Integer unmapGranularity;
    public String unmapPriority;
    public VmfsUnmapBandwidthSpec unmapBandwidthSpec;
    public int maxBlocks;
    public int majorVersion;
    public String version;
    public String uuid;
    private final static HostScsiDiskPartition[] NULL_EXTENT_ARRAY = new HostScsiDiskPartition[ 0 ] ;
    public HostScsiDiskPartition[] extent;
    public boolean vmfsUpgradable;
    public HostForceMountedInfo forceMountedInfo;
    public Boolean ssd;
    public Boolean local;
    public String scsiDiskType;

    public int getBlockSizeMb() {
        return blockSizeMb;
    }

    public void setBlockSizeMb(int blockSizeMb) {
        this.blockSizeMb = blockSizeMb;
    }

    public Integer getBlockSize() {
        return blockSize;
    }

    public void setBlockSize(Integer blockSize) {
        this.blockSize = blockSize;
    }

    public Integer getUnmapGranularity() {
        return unmapGranularity;
    }

    public void setUnmapGranularity(Integer unmapGranularity) {
        this.unmapGranularity = unmapGranularity;
    }

    public String getUnmapPriority() {
        return unmapPriority;
    }

    public void setUnmapPriority(String unmapPriority) {
        this.unmapPriority = unmapPriority;
    }

    public VmfsUnmapBandwidthSpec getUnmapBandwidthSpec() {
        return unmapBandwidthSpec;
    }

    public void setUnmapBandwidthSpec(VmfsUnmapBandwidthSpec unmapBandwidthSpec) {
        this.unmapBandwidthSpec = unmapBandwidthSpec;
    }

    public int getMaxBlocks() {
        return maxBlocks;
    }

    public void setMaxBlocks(int maxBlocks) {
        this.maxBlocks = maxBlocks;
    }

    public int getMajorVersion() {
        return majorVersion;
    }

    public void setMajorVersion(int majorVersion) {
        this.majorVersion = majorVersion;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public HostScsiDiskPartition[] getExtent() {
        if ((extent) == null) {
            return (NULL_EXTENT_ARRAY);
        }
        return extent;
    }

    public void setExtent(HostScsiDiskPartition[] extent) {
        this.extent = extent;
    }

    public boolean getVmfsUpgradable() {
        return vmfsUpgradable;
    }

    public void setVmfsUpgradable(boolean vmfsUpgradable) {
        this.vmfsUpgradable = vmfsUpgradable;
    }

    public boolean isVmfsUpgradable() {
        return vmfsUpgradable;
    }

    public HostForceMountedInfo getForceMountedInfo() {
        return forceMountedInfo;
    }

    public void setForceMountedInfo(HostForceMountedInfo forceMountedInfo) {
        this.forceMountedInfo = forceMountedInfo;
    }

    public Boolean getSsd() {
        return ssd;
    }

    public void setSsd(Boolean ssd) {
        this.ssd = ssd;
    }

    public Boolean isSsd() {
        return ssd;
    }

    public Boolean getLocal() {
        return local;
    }

    public void setLocal(Boolean local) {
        this.local = local;
    }

    public Boolean isLocal() {
        return local;
    }

    public String getScsiDiskType() {
        return scsiDiskType;
    }

    public void setScsiDiskType(String scsiDiskType) {
        this.scsiDiskType = scsiDiskType;
    }

}
