//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostTpmSoftwareComponentEventDetails
    extends HostTpmEventDetails
{

    public String componentName;
    public String vibName;
    public String vibVersion;
    public String vibVendor;

    public String getComponentName() {
        return componentName;
    }

    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    public String getVibName() {
        return vibName;
    }

    public void setVibName(String vibName) {
        this.vibName = vibName;
    }

    public String getVibVersion() {
        return vibVersion;
    }

    public void setVibVersion(String vibVersion) {
        this.vibVersion = vibVersion;
    }

    public String getVibVendor() {
        return vibVendor;
    }

    public void setVibVendor(String vibVendor) {
        this.vibVendor = vibVendor;
    }

}
