//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostVirtualNicManagerNicTypeSelection
    extends DynamicData
{

    public HostVirtualNicConnection vnic;
    private final static String[] NULL_NIC_TYPE_ARRAY = new String[ 0 ] ;
    public String[] nicType;

    public HostVirtualNicConnection getVnic() {
        return vnic;
    }

    public void setVnic(HostVirtualNicConnection vnic) {
        this.vnic = vnic;
    }

    public String[] getNicType() {
        if ((nicType) == null) {
            return (NULL_NIC_TYPE_ARRAY);
        }
        return nicType;
    }

    public void setNicType(String[] nicType) {
        this.nicType = nicType;
    }

}
