//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostStorageDeviceInfo
    extends DynamicData
{

    private final static HostHostBusAdapter[] NULL_HOST_BUS_ADAPTER_ARRAY = new HostHostBusAdapter[ 0 ] ;
    public HostHostBusAdapter[] hostBusAdapter;
    private final static ScsiLun[] NULL_SCSI_LUN_ARRAY = new ScsiLun[ 0 ] ;
    public ScsiLun[] scsiLun;
    public HostScsiTopology scsiTopology;
    public HostMultipathInfo multipathInfo;
    public HostPlugStoreTopology plugStoreTopology;
    public boolean softwareInternetScsiEnabled;

    public HostHostBusAdapter[] getHostBusAdapter() {
        if ((hostBusAdapter) == null) {
            return (NULL_HOST_BUS_ADAPTER_ARRAY);
        }
        return hostBusAdapter;
    }

    public void setHostBusAdapter(HostHostBusAdapter[] hostBusAdapter) {
        this.hostBusAdapter = hostBusAdapter;
    }

    public ScsiLun[] getScsiLun() {
        if ((scsiLun) == null) {
            return (NULL_SCSI_LUN_ARRAY);
        }
        return scsiLun;
    }

    public void setScsiLun(ScsiLun[] scsiLun) {
        this.scsiLun = scsiLun;
    }

    public HostScsiTopology getScsiTopology() {
        return scsiTopology;
    }

    public void setScsiTopology(HostScsiTopology scsiTopology) {
        this.scsiTopology = scsiTopology;
    }

    public HostMultipathInfo getMultipathInfo() {
        return multipathInfo;
    }

    public void setMultipathInfo(HostMultipathInfo multipathInfo) {
        this.multipathInfo = multipathInfo;
    }

    public HostPlugStoreTopology getPlugStoreTopology() {
        return plugStoreTopology;
    }

    public void setPlugStoreTopology(HostPlugStoreTopology plugStoreTopology) {
        this.plugStoreTopology = plugStoreTopology;
    }

    public boolean getSoftwareInternetScsiEnabled() {
        return softwareInternetScsiEnabled;
    }

    public void setSoftwareInternetScsiEnabled(boolean softwareInternetScsiEnabled) {
        this.softwareInternetScsiEnabled = softwareInternetScsiEnabled;
    }

    public boolean isSoftwareInternetScsiEnabled() {
        return softwareInternetScsiEnabled;
    }

}
