//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostPlugStoreTopologyPlugin
    extends DynamicData
{

    public String key;
    public String name;
    private final static String[] NULL_DEVICE_ARRAY = new String[ 0 ] ;
    public String[] device;
    private final static String[] NULL_CLAIMED_PATH_ARRAY = new String[ 0 ] ;
    public String[] claimedPath;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String[] getDevice() {
        if ((device) == null) {
            return (NULL_DEVICE_ARRAY);
        }
        return device;
    }

    public void setDevice(String[] device) {
        this.device = device;
    }

    public String[] getClaimedPath() {
        if ((claimedPath) == null) {
            return (NULL_CLAIMED_PATH_ARRAY);
        }
        return claimedPath;
    }

    public void setClaimedPath(String[] claimedPath) {
        this.claimedPath = claimedPath;
    }

}
