//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostDatastoreSystemCapabilities
    extends DynamicData
{

    public boolean nfsMountCreationRequired;
    public boolean nfsMountCreationSupported;
    public boolean localDatastoreSupported;
    public Boolean vmfsExtentExpansionSupported;

    public boolean getNfsMountCreationRequired() {
        return nfsMountCreationRequired;
    }

    public void setNfsMountCreationRequired(boolean nfsMountCreationRequired) {
        this.nfsMountCreationRequired = nfsMountCreationRequired;
    }

    public boolean isNfsMountCreationRequired() {
        return nfsMountCreationRequired;
    }

    public boolean getNfsMountCreationSupported() {
        return nfsMountCreationSupported;
    }

    public void setNfsMountCreationSupported(boolean nfsMountCreationSupported) {
        this.nfsMountCreationSupported = nfsMountCreationSupported;
    }

    public boolean isNfsMountCreationSupported() {
        return nfsMountCreationSupported;
    }

    public boolean getLocalDatastoreSupported() {
        return localDatastoreSupported;
    }

    public void setLocalDatastoreSupported(boolean localDatastoreSupported) {
        this.localDatastoreSupported = localDatastoreSupported;
    }

    public boolean isLocalDatastoreSupported() {
        return localDatastoreSupported;
    }

    public Boolean getVmfsExtentExpansionSupported() {
        return vmfsExtentExpansionSupported;
    }

    public void setVmfsExtentExpansionSupported(Boolean vmfsExtentExpansionSupported) {
        this.vmfsExtentExpansionSupported = vmfsExtentExpansionSupported;
    }

    public Boolean isVmfsExtentExpansionSupported() {
        return vmfsExtentExpansionSupported;
    }

}
