//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostDatastoreBrowserSearchSpec
    extends DynamicData
{

    private final static FileQuery[] NULL_QUERY_ARRAY = new FileQuery[ 0 ] ;
    public FileQuery[] query;
    public FileQueryFlags details;
    public Boolean searchCaseInsensitive;
    private final static String[] NULL_MATCH_PATTERN_ARRAY = new String[ 0 ] ;
    public String[] matchPattern;
    public Boolean sortFoldersFirst;

    public FileQuery[] getQuery() {
        if ((query) == null) {
            return (NULL_QUERY_ARRAY);
        }
        return query;
    }

    public void setQuery(FileQuery[] query) {
        this.query = query;
    }

    public FileQueryFlags getDetails() {
        return details;
    }

    public void setDetails(FileQueryFlags details) {
        this.details = details;
    }

    public Boolean getSearchCaseInsensitive() {
        return searchCaseInsensitive;
    }

    public void setSearchCaseInsensitive(Boolean searchCaseInsensitive) {
        this.searchCaseInsensitive = searchCaseInsensitive;
    }

    public Boolean isSearchCaseInsensitive() {
        return searchCaseInsensitive;
    }

    public String[] getMatchPattern() {
        if ((matchPattern) == null) {
            return (NULL_MATCH_PATTERN_ARRAY);
        }
        return matchPattern;
    }

    public void setMatchPattern(String[] matchPattern) {
        this.matchPattern = matchPattern;
    }

    public Boolean getSortFoldersFirst() {
        return sortFoldersFirst;
    }

    public void setSortFoldersFirst(Boolean sortFoldersFirst) {
        this.sortFoldersFirst = sortFoldersFirst;
    }

    public Boolean isSortFoldersFirst() {
        return sortFoldersFirst;
    }

}
