//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostVirtualNicConnection
    extends DynamicData
{

    public String portgroup;
    public DistributedVirtualSwitchPortConnection dvPort;
    public HostVirtualNicOpaqueNetworkSpec opNetwork;

    public String getPortgroup() {
        return portgroup;
    }

    public void setPortgroup(String portgroup) {
        this.portgroup = portgroup;
    }

    public DistributedVirtualSwitchPortConnection getDvPort() {
        return dvPort;
    }

    public void setDvPort(DistributedVirtualSwitchPortConnection dvPort) {
        this.dvPort = dvPort;
    }

    public HostVirtualNicOpaqueNetworkSpec getOpNetwork() {
        return opNetwork;
    }

    public void setOpNetwork(HostVirtualNicOpaqueNetworkSpec opNetwork) {
        this.opNetwork = opNetwork;
    }

}
