//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostSriovInfo
    extends HostPciPassthruInfo
{

    public boolean sriovEnabled;
    public boolean sriovCapable;
    public boolean sriovActive;
    public int numVirtualFunctionRequested;
    public int numVirtualFunction;
    public int maxVirtualFunctionSupported;

    public boolean getSriovEnabled() {
        return sriovEnabled;
    }

    public void setSriovEnabled(boolean sriovEnabled) {
        this.sriovEnabled = sriovEnabled;
    }

    public boolean isSriovEnabled() {
        return sriovEnabled;
    }

    public boolean getSriovCapable() {
        return sriovCapable;
    }

    public void setSriovCapable(boolean sriovCapable) {
        this.sriovCapable = sriovCapable;
    }

    public boolean isSriovCapable() {
        return sriovCapable;
    }

    public boolean getSriovActive() {
        return sriovActive;
    }

    public void setSriovActive(boolean sriovActive) {
        this.sriovActive = sriovActive;
    }

    public boolean isSriovActive() {
        return sriovActive;
    }

    public int getNumVirtualFunctionRequested() {
        return numVirtualFunctionRequested;
    }

    public void setNumVirtualFunctionRequested(int numVirtualFunctionRequested) {
        this.numVirtualFunctionRequested = numVirtualFunctionRequested;
    }

    public int getNumVirtualFunction() {
        return numVirtualFunction;
    }

    public void setNumVirtualFunction(int numVirtualFunction) {
        this.numVirtualFunction = numVirtualFunction;
    }

    public int getMaxVirtualFunctionSupported() {
        return maxVirtualFunctionSupported;
    }

    public void setMaxVirtualFunctionSupported(int maxVirtualFunctionSupported) {
        this.maxVirtualFunctionSupported = maxVirtualFunctionSupported;
    }

}
