//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class HostSystemHealthInfo
    extends DynamicData
{

    private final static HostNumericSensorInfo[] NULL_NUMERIC_SENSOR_INFO_ARRAY = new HostNumericSensorInfo[ 0 ] ;
    public HostNumericSensorInfo[] numericSensorInfo;

    public HostNumericSensorInfo[] getNumericSensorInfo() {
        if ((numericSensorInfo) == null) {
            return (NULL_NUMERIC_SENSOR_INFO_ARRAY);
        }
        return numericSensorInfo;
    }

    public void setNumericSensorInfo(HostNumericSensorInfo[] numericSensorInfo) {
        this.numericSensorInfo = numericSensorInfo;
    }

}
