//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class HostIpRouteConfig
    extends DynamicData
{

    public String defaultGateway;
    public String gatewayDevice;
    public String ipV6DefaultGateway;
    public String ipV6GatewayDevice;

    public String getDefaultGateway() {
        return defaultGateway;
    }

    public void setDefaultGateway(String defaultGateway) {
        this.defaultGateway = defaultGateway;
    }

    public String getGatewayDevice() {
        return gatewayDevice;
    }

    public void setGatewayDevice(String gatewayDevice) {
        this.gatewayDevice = gatewayDevice;
    }

    public String getIpV6DefaultGateway() {
        return ipV6DefaultGateway;
    }

    public void setIpV6DefaultGateway(String ipV6DefaultGateway) {
        this.ipV6DefaultGateway = ipV6DefaultGateway;
    }

    public String getIpV6GatewayDevice() {
        return ipV6GatewayDevice;
    }

    public void setIpV6GatewayDevice(String ipV6GatewayDevice) {
        this.ipV6GatewayDevice = ipV6GatewayDevice;
    }

}
