//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class InsufficientAgentVmsDeployed
    extends InsufficientResourcesFault
{

    public String hostName;
    public int requiredNumAgentVms;
    public int currentNumAgentVms;

    public String getHostName() {
        return hostName;
    }

    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    public int getRequiredNumAgentVms() {
        return requiredNumAgentVms;
    }

    public void setRequiredNumAgentVms(int requiredNumAgentVms) {
        this.requiredNumAgentVms = requiredNumAgentVms;
    }

    public int getCurrentNumAgentVms() {
        return currentNumAgentVms;
    }

    public void setCurrentNumAgentVms(int currentNumAgentVms) {
        this.currentNumAgentVms = currentNumAgentVms;
    }

}
