//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class IoFilterHostIssue
    extends DynamicData
{

    public ManagedObjectReference host;
    private final static LocalizedMethodFault[] NULL_ISSUE_ARRAY = new LocalizedMethodFault[ 0 ] ;
    public LocalizedMethodFault[] issue;

    public ManagedObjectReference getHost() {
        return host;
    }

    public void setHost(ManagedObjectReference host) {
        this.host = host;
    }

    public LocalizedMethodFault[] getIssue() {
        if ((issue) == null) {
            return (NULL_ISSUE_ARRAY);
        }
        return issue;
    }

    public void setIssue(LocalizedMethodFault[] issue) {
        this.issue = issue;
    }

}
