//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class IpRouteProfile
    extends ApplyProfile
{

    private final static StaticRouteProfile[] NULL_STATIC_ROUTE_ARRAY = new StaticRouteProfile[ 0 ] ;
    public StaticRouteProfile[] staticRoute;

    public StaticRouteProfile[] getStaticRoute() {
        if ((staticRoute) == null) {
            return (NULL_STATIC_ROUTE_ARRAY);
        }
        return staticRoute;
    }

    public void setStaticRoute(StaticRouteProfile[] staticRoute) {
        this.staticRoute = staticRoute;
    }

}
