//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class KmipClusterInfo
    extends DynamicData
{

    public KeyProviderId clusterId;
    private final static KmipServerInfo[] NULL_SERVERS_ARRAY = new KmipServerInfo[ 0 ] ;
    public KmipServerInfo[] servers;
    public boolean useAsDefault;

    public KeyProviderId getClusterId() {
        return clusterId;
    }

    public void setClusterId(KeyProviderId clusterId) {
        this.clusterId = clusterId;
    }

    public KmipServerInfo[] getServers() {
        if ((servers) == null) {
            return (NULL_SERVERS_ARRAY);
        }
        return servers;
    }

    public void setServers(KmipServerInfo[] servers) {
        this.servers = servers;
    }

    public boolean getUseAsDefault() {
        return useAsDefault;
    }

    public void setUseAsDefault(boolean useAsDefault) {
        this.useAsDefault = useAsDefault;
    }

    public boolean isUseAsDefault() {
        return useAsDefault;
    }

}
