//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;

import java.util.Calendar;


/**
 * 
 */
@SuppressWarnings("all")
public class LicenseDiagnostics
    extends DynamicData
{

    public Calendar sourceLastChanged;
    public String sourceLost;
    public float sourceLatency;
    public String licenseRequests;
    public String licenseRequestFailures;
    public String licenseFeatureUnknowns;
    public LicenseManagerState opState;
    public Calendar lastStatusUpdate;
    public String opFailureMessage;

    public Calendar getSourceLastChanged() {
        return sourceLastChanged;
    }

    public void setSourceLastChanged(Calendar sourceLastChanged) {
        this.sourceLastChanged = sourceLastChanged;
    }

    public String getSourceLost() {
        return sourceLost;
    }

    public void setSourceLost(String sourceLost) {
        this.sourceLost = sourceLost;
    }

    public float getSourceLatency() {
        return sourceLatency;
    }

    public void setSourceLatency(float sourceLatency) {
        this.sourceLatency = sourceLatency;
    }

    public String getLicenseRequests() {
        return licenseRequests;
    }

    public void setLicenseRequests(String licenseRequests) {
        this.licenseRequests = licenseRequests;
    }

    public String getLicenseRequestFailures() {
        return licenseRequestFailures;
    }

    public void setLicenseRequestFailures(String licenseRequestFailures) {
        this.licenseRequestFailures = licenseRequestFailures;
    }

    public String getLicenseFeatureUnknowns() {
        return licenseFeatureUnknowns;
    }

    public void setLicenseFeatureUnknowns(String licenseFeatureUnknowns) {
        this.licenseFeatureUnknowns = licenseFeatureUnknowns;
    }

    public LicenseManagerState getOpState() {
        return opState;
    }

    public void setOpState(LicenseManagerState opState) {
        this.opState = opState;
    }

    public Calendar getLastStatusUpdate() {
        return lastStatusUpdate;
    }

    public void setLastStatusUpdate(Calendar lastStatusUpdate) {
        this.lastStatusUpdate = lastStatusUpdate;
    }

    public String getOpFailureMessage() {
        return opFailureMessage;
    }

    public void setOpFailureMessage(String opFailureMessage) {
        this.opFailureMessage = opFailureMessage;
    }

}
