//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class LicenseAssignmentManagerLicenseAssignment
    extends DynamicData
{

    public String entityId;
    public String scope;
    public String entityDisplayName;
    public LicenseManagerLicenseInfo assignedLicense;
    private final static KeyAnyValue[] NULL_PROPERTIES_ARRAY = new KeyAnyValue[ 0 ] ;
    public KeyAnyValue[] properties;

    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getEntityDisplayName() {
        return entityDisplayName;
    }

    public void setEntityDisplayName(String entityDisplayName) {
        this.entityDisplayName = entityDisplayName;
    }

    public LicenseManagerLicenseInfo getAssignedLicense() {
        return assignedLicense;
    }

    public void setAssignedLicense(LicenseManagerLicenseInfo assignedLicense) {
        this.assignedLicense = assignedLicense;
    }

    public KeyAnyValue[] getProperties() {
        if ((properties) == null) {
            return (NULL_PROPERTIES_ARRAY);
        }
        return properties;
    }

    public void setProperties(KeyAnyValue[] properties) {
        this.properties = properties;
    }

}
