//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class LinkLayerDiscoveryProtocolInfo
    extends DynamicData
{

    public String chassisId;
    public String portId;
    public int timeToLive;
    private final static KeyAnyValue[] NULL_PARAMETER_ARRAY = new KeyAnyValue[ 0 ] ;
    public KeyAnyValue[] parameter;

    public String getChassisId() {
        return chassisId;
    }

    public void setChassisId(String chassisId) {
        this.chassisId = chassisId;
    }

    public String getPortId() {
        return portId;
    }

    public void setPortId(String portId) {
        this.portId = portId;
    }

    public int getTimeToLive() {
        return timeToLive;
    }

    public void setTimeToLive(int timeToLive) {
        this.timeToLive = timeToLive;
    }

    public KeyAnyValue[] getParameter() {
        if ((parameter) == null) {
            return (NULL_PARAMETER_ARRAY);
        }
        return parameter;
    }

    public void setParameter(KeyAnyValue[] parameter) {
        this.parameter = parameter;
    }

}
