//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class LocalizableMessage
    extends DynamicData
{

    public String key;
    private final static KeyAnyValue[] NULL_ARG_ARRAY = new KeyAnyValue[ 0 ] ;
    public KeyAnyValue[] arg;
    public String message;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public KeyAnyValue[] getArg() {
        if ((arg) == null) {
            return (NULL_ARG_ARRAY);
        }
        return arg;
    }

    public void setArg(KeyAnyValue[] arg) {
        this.arg = arg;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

}
