//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class NetIpRouteConfigSpecIpRouteSpec
    extends DynamicData
{

    public String network;
    public int prefixLength;
    public NetIpRouteConfigSpecGatewaySpec gateway;
    public String operation;

    public String getNetwork() {
        return network;
    }

    public void setNetwork(String network) {
        this.network = network;
    }

    public int getPrefixLength() {
        return prefixLength;
    }

    public void setPrefixLength(int prefixLength) {
        this.prefixLength = prefixLength;
    }

    public NetIpRouteConfigSpecGatewaySpec getGateway() {
        return gateway;
    }

    public void setGateway(NetIpRouteConfigSpecGatewaySpec gateway) {
        this.gateway = gateway;
    }

    public String getOperation() {
        return operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

}
