//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class NvdimmSystemInfo
    extends DynamicData
{

    public NvdimmSummary summary;
    private final static int[] NULL_DIMMS_ARRAY = new int[ 0 ] ;
    public int[] dimms;
    private final static NvdimmDimmInfo[] NULL_DIMM_INFO_ARRAY = new NvdimmDimmInfo[ 0 ] ;
    public NvdimmDimmInfo[] dimmInfo;
    private final static int[] NULL_INTERLEAVE_SET_ARRAY = new int[ 0 ] ;
    public int[] interleaveSet;
    private final static NvdimmInterleaveSetInfo[] NULL_I_SET_INFO_ARRAY = new NvdimmInterleaveSetInfo[ 0 ] ;
    public NvdimmInterleaveSetInfo[] iSetInfo;
    private final static NvdimmGuid[] NULL_NAMESPACE_ARRAY = new NvdimmGuid[ 0 ] ;
    public NvdimmGuid[] namespace;
    private final static NvdimmNamespaceInfo[] NULL_NS_INFO_ARRAY = new NvdimmNamespaceInfo[ 0 ] ;
    public NvdimmNamespaceInfo[] nsInfo;

    public NvdimmSummary getSummary() {
        return summary;
    }

    public void setSummary(NvdimmSummary summary) {
        this.summary = summary;
    }

    public int[] getDimms() {
        if ((dimms) == null) {
            return (NULL_DIMMS_ARRAY);
        }
        return dimms;
    }

    public void setDimms(int[] dimms) {
        this.dimms = dimms;
    }

    public NvdimmDimmInfo[] getDimmInfo() {
        if ((dimmInfo) == null) {
            return (NULL_DIMM_INFO_ARRAY);
        }
        return dimmInfo;
    }

    public void setDimmInfo(NvdimmDimmInfo[] dimmInfo) {
        this.dimmInfo = dimmInfo;
    }

    public int[] getInterleaveSet() {
        if ((interleaveSet) == null) {
            return (NULL_INTERLEAVE_SET_ARRAY);
        }
        return interleaveSet;
    }

    public void setInterleaveSet(int[] interleaveSet) {
        this.interleaveSet = interleaveSet;
    }

    public NvdimmInterleaveSetInfo[] getISetInfo() {
        if ((iSetInfo) == null) {
            return (NULL_I_SET_INFO_ARRAY);
        }
        return iSetInfo;
    }

    public void setISetInfo(NvdimmInterleaveSetInfo[] iSetInfo) {
        this.iSetInfo = iSetInfo;
    }

    public NvdimmGuid[] getNamespace() {
        if ((namespace) == null) {
            return (NULL_NAMESPACE_ARRAY);
        }
        return namespace;
    }

    public void setNamespace(NvdimmGuid[] namespace) {
        this.namespace = namespace;
    }

    public NvdimmNamespaceInfo[] getNsInfo() {
        if ((nsInfo) == null) {
            return (NULL_NS_INFO_ARRAY);
        }
        return nsInfo;
    }

    public void setNsInfo(NvdimmNamespaceInfo[] nsInfo) {
        this.nsInfo = nsInfo;
    }

}
