//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class NvdimmInterleaveSetInfo
    extends DynamicData
{

    public int setId;
    public String rangeType;
    public long baseAddress;
    public long size;
    public long availableSize;
    private final static int[] NULL_DEVICE_LIST_ARRAY = new int[ 0 ] ;
    public int[] deviceList;
    public String state;

    public int getSetId() {
        return setId;
    }

    public void setSetId(int setId) {
        this.setId = setId;
    }

    public String getRangeType() {
        return rangeType;
    }

    public void setRangeType(String rangeType) {
        this.rangeType = rangeType;
    }

    public long getBaseAddress() {
        return baseAddress;
    }

    public void setBaseAddress(long baseAddress) {
        this.baseAddress = baseAddress;
    }

    public long getSize() {
        return size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    public long getAvailableSize() {
        return availableSize;
    }

    public void setAvailableSize(long availableSize) {
        this.availableSize = availableSize;
    }

    public int[] getDeviceList() {
        if ((deviceList) == null) {
            return (NULL_DEVICE_LIST_ARRAY);
        }
        return deviceList;
    }

    public void setDeviceList(int[] deviceList) {
        this.deviceList = deviceList;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

}
