//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class OvfMappedOsId
    extends OvfImport
{

    public int ovfId;
    public String ovfDescription;
    public String targetDescription;

    public int getOvfId() {
        return ovfId;
    }

    public void setOvfId(int ovfId) {
        this.ovfId = ovfId;
    }

    public String getOvfDescription() {
        return ovfDescription;
    }

    public void setOvfDescription(String ovfDescription) {
        this.ovfDescription = ovfDescription;
    }

    public String getTargetDescription() {
        return targetDescription;
    }

    public void setTargetDescription(String targetDescription) {
        this.targetDescription = targetDescription;
    }

}
