//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class PlacementAction
    extends ClusterAction
{

    public ManagedObjectReference vm;
    public ManagedObjectReference targetHost;
    public VirtualMachineRelocateSpec relocateSpec;

    public ManagedObjectReference getVm() {
        return vm;
    }

    public void setVm(ManagedObjectReference vm) {
        this.vm = vm;
    }

    public ManagedObjectReference getTargetHost() {
        return targetHost;
    }

    public void setTargetHost(ManagedObjectReference targetHost) {
        this.targetHost = targetHost;
    }

    public VirtualMachineRelocateSpec getRelocateSpec() {
        return relocateSpec;
    }

    public void setRelocateSpec(VirtualMachineRelocateSpec relocateSpec) {
        this.relocateSpec = relocateSpec;
    }

}
