//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class PortGroupProfile
    extends ApplyProfile
{

    public String key;
    public String name;
    public VlanProfile vlan;
    public VirtualSwitchSelectionProfile vswitch;
    public NetworkPolicyProfile networkPolicy;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public VlanProfile getVlan() {
        return vlan;
    }

    public void setVlan(VlanProfile vlan) {
        this.vlan = vlan;
    }

    public VirtualSwitchSelectionProfile getVswitch() {
        return vswitch;
    }

    public void setVswitch(VirtualSwitchSelectionProfile vswitch) {
        this.vswitch = vswitch;
    }

    public NetworkPolicyProfile getNetworkPolicy() {
        return networkPolicy;
    }

    public void setNetworkPolicy(NetworkPolicyProfile networkPolicy) {
        this.networkPolicy = networkPolicy;
    }

}
