//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class PrivilegePolicyDef
    extends DynamicData
{

    public String createPrivilege;
    public String readPrivilege;
    public String updatePrivilege;
    public String deletePrivilege;

    public String getCreatePrivilege() {
        return createPrivilege;
    }

    public void setCreatePrivilege(String createPrivilege) {
        this.createPrivilege = createPrivilege;
    }

    public String getReadPrivilege() {
        return readPrivilege;
    }

    public void setReadPrivilege(String readPrivilege) {
        this.readPrivilege = readPrivilege;
    }

    public String getUpdatePrivilege() {
        return updatePrivilege;
    }

    public void setUpdatePrivilege(String updatePrivilege) {
        this.updatePrivilege = updatePrivilege;
    }

    public String getDeletePrivilege() {
        return deletePrivilege;
    }

    public void setDeletePrivilege(String deletePrivilege) {
        this.deletePrivilege = deletePrivilege;
    }

}
