//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ProfileProfileStructureProperty
    extends DynamicData
{

    public String propertyName;
    public boolean array;
    public ProfileProfileStructure element;

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public boolean getArray() {
        return array;
    }

    public void setArray(boolean array) {
        this.array = array;
    }

    public boolean isArray() {
        return array;
    }

    public ProfileProfileStructure getElement() {
        return element;
    }

    public void setElement(ProfileProfileStructure element) {
        this.element = element;
    }

}
