//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class RoleAddedEvent
    extends RoleEvent
{

    private final static String[] NULL_PRIVILEGE_LIST_ARRAY = new String[ 0 ] ;
    public String[] privilegeList;

    public String[] getPrivilegeList() {
        if ((privilegeList) == null) {
            return (NULL_PRIVILEGE_LIST_ARRAY);
        }
        return privilegeList;
    }

    public void setPrivilegeList(String[] privilegeList) {
        this.privilegeList = privilegeList;
    }

}
