//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class ScheduledTaskDescription
    extends DynamicData
{

    private final static TypeDescription[] NULL_ACTION_ARRAY = new TypeDescription[ 0 ] ;
    public TypeDescription[] action;
    private final static ScheduledTaskDetail[] NULL_SCHEDULER_INFO_ARRAY = new ScheduledTaskDetail[ 0 ] ;
    public ScheduledTaskDetail[] schedulerInfo;
    private final static ElementDescription[] NULL_STATE_ARRAY = new ElementDescription[ 0 ] ;
    public ElementDescription[] state;
    private final static ElementDescription[] NULL_DAY_OF_WEEK_ARRAY = new ElementDescription[ 0 ] ;
    public ElementDescription[] dayOfWeek;
    private final static ElementDescription[] NULL_WEEK_OF_MONTH_ARRAY = new ElementDescription[ 0 ] ;
    public ElementDescription[] weekOfMonth;

    public TypeDescription[] getAction() {
        if ((action) == null) {
            return (NULL_ACTION_ARRAY);
        }
        return action;
    }

    public void setAction(TypeDescription[] action) {
        this.action = action;
    }

    public ScheduledTaskDetail[] getSchedulerInfo() {
        if ((schedulerInfo) == null) {
            return (NULL_SCHEDULER_INFO_ARRAY);
        }
        return schedulerInfo;
    }

    public void setSchedulerInfo(ScheduledTaskDetail[] schedulerInfo) {
        this.schedulerInfo = schedulerInfo;
    }

    public ElementDescription[] getState() {
        if ((state) == null) {
            return (NULL_STATE_ARRAY);
        }
        return state;
    }

    public void setState(ElementDescription[] state) {
        this.state = state;
    }

    public ElementDescription[] getDayOfWeek() {
        if ((dayOfWeek) == null) {
            return (NULL_DAY_OF_WEEK_ARRAY);
        }
        return dayOfWeek;
    }

    public void setDayOfWeek(ElementDescription[] dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    public ElementDescription[] getWeekOfMonth() {
        if ((weekOfMonth) == null) {
            return (NULL_WEEK_OF_MONTH_ARRAY);
        }
        return weekOfMonth;
    }

    public void setWeekOfMonth(ElementDescription[] weekOfMonth) {
        this.weekOfMonth = weekOfMonth;
    }

}
