//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class StorageDrsPlacementRankVmSpec
    extends DynamicData
{

    public PlacementSpec vmPlacementSpec;
    private final static ManagedObjectReference[] NULL_VM_CLUSTERS_ARRAY = new ManagedObjectReference[ 0 ] ;
    public ManagedObjectReference[] vmClusters;

    public PlacementSpec getVmPlacementSpec() {
        return vmPlacementSpec;
    }

    public void setVmPlacementSpec(PlacementSpec vmPlacementSpec) {
        this.vmPlacementSpec = vmPlacementSpec;
    }

    public ManagedObjectReference[] getVmClusters() {
        if ((vmClusters) == null) {
            return (NULL_VM_CLUSTERS_ARRAY);
        }
        return vmClusters;
    }

    public void setVmClusters(ManagedObjectReference[] vmClusters) {
        this.vmClusters = vmClusters;
    }

}
