//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class StorageIORMInfo
    extends DynamicData
{

    public boolean enabled;
    public String congestionThresholdMode;
    public int congestionThreshold;
    public Integer percentOfPeakThroughput;
    public Boolean statsCollectionEnabled;
    public Boolean reservationEnabled;
    public Boolean statsAggregationDisabled;
    public Integer reservableIopsThreshold;

    public boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public String getCongestionThresholdMode() {
        return congestionThresholdMode;
    }

    public void setCongestionThresholdMode(String congestionThresholdMode) {
        this.congestionThresholdMode = congestionThresholdMode;
    }

    public int getCongestionThreshold() {
        return congestionThreshold;
    }

    public void setCongestionThreshold(int congestionThreshold) {
        this.congestionThreshold = congestionThreshold;
    }

    public Integer getPercentOfPeakThroughput() {
        return percentOfPeakThroughput;
    }

    public void setPercentOfPeakThroughput(Integer percentOfPeakThroughput) {
        this.percentOfPeakThroughput = percentOfPeakThroughput;
    }

    public Boolean getStatsCollectionEnabled() {
        return statsCollectionEnabled;
    }

    public void setStatsCollectionEnabled(Boolean statsCollectionEnabled) {
        this.statsCollectionEnabled = statsCollectionEnabled;
    }

    public Boolean isStatsCollectionEnabled() {
        return statsCollectionEnabled;
    }

    public Boolean getReservationEnabled() {
        return reservationEnabled;
    }

    public void setReservationEnabled(Boolean reservationEnabled) {
        this.reservationEnabled = reservationEnabled;
    }

    public Boolean isReservationEnabled() {
        return reservationEnabled;
    }

    public Boolean getStatsAggregationDisabled() {
        return statsAggregationDisabled;
    }

    public void setStatsAggregationDisabled(Boolean statsAggregationDisabled) {
        this.statsAggregationDisabled = statsAggregationDisabled;
    }

    public Boolean isStatsAggregationDisabled() {
        return statsAggregationDisabled;
    }

    public Integer getReservableIopsThreshold() {
        return reservableIopsThreshold;
    }

    public void setReservableIopsThreshold(Integer reservableIopsThreshold) {
        this.reservableIopsThreshold = reservableIopsThreshold;
    }

}
