//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class StorageDrsVmConfigInfo
    extends DynamicData
{

    public ManagedObjectReference vm;
    public Boolean enabled;
    public String behavior;
    public Boolean intraVmAffinity;
    public VirtualDiskAntiAffinityRuleSpec intraVmAntiAffinity;
    private final static VirtualDiskRuleSpec[] NULL_VIRTUAL_DISK_RULES_ARRAY = new VirtualDiskRuleSpec[ 0 ] ;
    public VirtualDiskRuleSpec[] virtualDiskRules;

    public ManagedObjectReference getVm() {
        return vm;
    }

    public void setVm(ManagedObjectReference vm) {
        this.vm = vm;
    }

    public Boolean getEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean isEnabled() {
        return enabled;
    }

    public String getBehavior() {
        return behavior;
    }

    public void setBehavior(String behavior) {
        this.behavior = behavior;
    }

    public Boolean getIntraVmAffinity() {
        return intraVmAffinity;
    }

    public void setIntraVmAffinity(Boolean intraVmAffinity) {
        this.intraVmAffinity = intraVmAffinity;
    }

    public Boolean isIntraVmAffinity() {
        return intraVmAffinity;
    }

    public VirtualDiskAntiAffinityRuleSpec getIntraVmAntiAffinity() {
        return intraVmAntiAffinity;
    }

    public void setIntraVmAntiAffinity(VirtualDiskAntiAffinityRuleSpec intraVmAntiAffinity) {
        this.intraVmAntiAffinity = intraVmAntiAffinity;
    }

    public VirtualDiskRuleSpec[] getVirtualDiskRules() {
        if ((virtualDiskRules) == null) {
            return (NULL_VIRTUAL_DISK_RULES_ARRAY);
        }
        return virtualDiskRules;
    }

    public void setVirtualDiskRules(VirtualDiskRuleSpec[] virtualDiskRules) {
        this.virtualDiskRules = virtualDiskRules;
    }

}
