//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class ToolsConfigInfo
    extends DynamicData
{

    public Integer toolsVersion;
    public String toolsInstallType;
    public Boolean afterPowerOn;
    public Boolean afterResume;
    public Boolean beforeGuestStandby;
    public Boolean beforeGuestShutdown;
    public Boolean beforeGuestReboot;
    public String toolsUpgradePolicy;
    public String pendingCustomization;
    public CryptoKeyId customizationKeyId;
    public Boolean syncTimeWithHost;
    public ToolsConfigInfoToolsLastInstallInfo lastInstallInfo;

    public Integer getToolsVersion() {
        return toolsVersion;
    }

    public void setToolsVersion(Integer toolsVersion) {
        this.toolsVersion = toolsVersion;
    }

    public String getToolsInstallType() {
        return toolsInstallType;
    }

    public void setToolsInstallType(String toolsInstallType) {
        this.toolsInstallType = toolsInstallType;
    }

    public Boolean getAfterPowerOn() {
        return afterPowerOn;
    }

    public void setAfterPowerOn(Boolean afterPowerOn) {
        this.afterPowerOn = afterPowerOn;
    }

    public Boolean isAfterPowerOn() {
        return afterPowerOn;
    }

    public Boolean getAfterResume() {
        return afterResume;
    }

    public void setAfterResume(Boolean afterResume) {
        this.afterResume = afterResume;
    }

    public Boolean isAfterResume() {
        return afterResume;
    }

    public Boolean getBeforeGuestStandby() {
        return beforeGuestStandby;
    }

    public void setBeforeGuestStandby(Boolean beforeGuestStandby) {
        this.beforeGuestStandby = beforeGuestStandby;
    }

    public Boolean isBeforeGuestStandby() {
        return beforeGuestStandby;
    }

    public Boolean getBeforeGuestShutdown() {
        return beforeGuestShutdown;
    }

    public void setBeforeGuestShutdown(Boolean beforeGuestShutdown) {
        this.beforeGuestShutdown = beforeGuestShutdown;
    }

    public Boolean isBeforeGuestShutdown() {
        return beforeGuestShutdown;
    }

    public Boolean getBeforeGuestReboot() {
        return beforeGuestReboot;
    }

    public void setBeforeGuestReboot(Boolean beforeGuestReboot) {
        this.beforeGuestReboot = beforeGuestReboot;
    }

    public Boolean isBeforeGuestReboot() {
        return beforeGuestReboot;
    }

    public String getToolsUpgradePolicy() {
        return toolsUpgradePolicy;
    }

    public void setToolsUpgradePolicy(String toolsUpgradePolicy) {
        this.toolsUpgradePolicy = toolsUpgradePolicy;
    }

    public String getPendingCustomization() {
        return pendingCustomization;
    }

    public void setPendingCustomization(String pendingCustomization) {
        this.pendingCustomization = pendingCustomization;
    }

    public CryptoKeyId getCustomizationKeyId() {
        return customizationKeyId;
    }

    public void setCustomizationKeyId(CryptoKeyId customizationKeyId) {
        this.customizationKeyId = customizationKeyId;
    }

    public Boolean getSyncTimeWithHost() {
        return syncTimeWithHost;
    }

    public void setSyncTimeWithHost(Boolean syncTimeWithHost) {
        this.syncTimeWithHost = syncTimeWithHost;
    }

    public Boolean isSyncTimeWithHost() {
        return syncTimeWithHost;
    }

    public ToolsConfigInfoToolsLastInstallInfo getLastInstallInfo() {
        return lastInstallInfo;
    }

    public void setLastInstallInfo(ToolsConfigInfoToolsLastInstallInfo lastInstallInfo) {
        this.lastInstallInfo = lastInstallInfo;
    }

}
