//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class UsbScanCodeSpecKeyEvent
    extends DynamicData
{

    public int usbHidCode;
    public UsbScanCodeSpecModifierType modifiers;

    public int getUsbHidCode() {
        return usbHidCode;
    }

    public void setUsbHidCode(int usbHidCode) {
        this.usbHidCode = usbHidCode;
    }

    public UsbScanCodeSpecModifierType getModifiers() {
        return modifiers;
    }

    public void setModifiers(UsbScanCodeSpecModifierType modifiers) {
        this.modifiers = modifiers;
    }

}
