//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class UsbScanCodeSpecModifierType
    extends DynamicData
{

    public Boolean leftControl;
    public Boolean leftShift;
    public Boolean leftAlt;
    public Boolean leftGui;
    public Boolean rightControl;
    public Boolean rightShift;
    public Boolean rightAlt;
    public Boolean rightGui;

    public Boolean getLeftControl() {
        return leftControl;
    }

    public void setLeftControl(Boolean leftControl) {
        this.leftControl = leftControl;
    }

    public Boolean isLeftControl() {
        return leftControl;
    }

    public Boolean getLeftShift() {
        return leftShift;
    }

    public void setLeftShift(Boolean leftShift) {
        this.leftShift = leftShift;
    }

    public Boolean isLeftShift() {
        return leftShift;
    }

    public Boolean getLeftAlt() {
        return leftAlt;
    }

    public void setLeftAlt(Boolean leftAlt) {
        this.leftAlt = leftAlt;
    }

    public Boolean isLeftAlt() {
        return leftAlt;
    }

    public Boolean getLeftGui() {
        return leftGui;
    }

    public void setLeftGui(Boolean leftGui) {
        this.leftGui = leftGui;
    }

    public Boolean isLeftGui() {
        return leftGui;
    }

    public Boolean getRightControl() {
        return rightControl;
    }

    public void setRightControl(Boolean rightControl) {
        this.rightControl = rightControl;
    }

    public Boolean isRightControl() {
        return rightControl;
    }

    public Boolean getRightShift() {
        return rightShift;
    }

    public void setRightShift(Boolean rightShift) {
        this.rightShift = rightShift;
    }

    public Boolean isRightShift() {
        return rightShift;
    }

    public Boolean getRightAlt() {
        return rightAlt;
    }

    public void setRightAlt(Boolean rightAlt) {
        this.rightAlt = rightAlt;
    }

    public Boolean isRightAlt() {
        return rightAlt;
    }

    public Boolean getRightGui() {
        return rightGui;
    }

    public void setRightGui(Boolean rightGui) {
        this.rightGui = rightGui;
    }

    public Boolean isRightGui() {
        return rightGui;
    }

}
