//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VAppCloneSpec
    extends DynamicData
{

    public ManagedObjectReference location;
    public ManagedObjectReference host;
    public ResourceConfigSpec resourceSpec;
    public ManagedObjectReference vmFolder;
    private final static VAppCloneSpecNetworkMappingPair[] NULL_NETWORK_MAPPING_ARRAY = new VAppCloneSpecNetworkMappingPair[ 0 ] ;
    public VAppCloneSpecNetworkMappingPair[] networkMapping;
    private final static KeyValue[] NULL_PROPERTY_ARRAY = new KeyValue[ 0 ] ;
    public KeyValue[] property;
    private final static VAppCloneSpecResourceMap[] NULL_RESOURCE_MAPPING_ARRAY = new VAppCloneSpecResourceMap[ 0 ] ;
    public VAppCloneSpecResourceMap[] resourceMapping;
    public String provisioning;

    public ManagedObjectReference getLocation() {
        return location;
    }

    public void setLocation(ManagedObjectReference location) {
        this.location = location;
    }

    public ManagedObjectReference getHost() {
        return host;
    }

    public void setHost(ManagedObjectReference host) {
        this.host = host;
    }

    public ResourceConfigSpec getResourceSpec() {
        return resourceSpec;
    }

    public void setResourceSpec(ResourceConfigSpec resourceSpec) {
        this.resourceSpec = resourceSpec;
    }

    public ManagedObjectReference getVmFolder() {
        return vmFolder;
    }

    public void setVmFolder(ManagedObjectReference vmFolder) {
        this.vmFolder = vmFolder;
    }

    public VAppCloneSpecNetworkMappingPair[] getNetworkMapping() {
        if ((networkMapping) == null) {
            return (NULL_NETWORK_MAPPING_ARRAY);
        }
        return networkMapping;
    }

    public void setNetworkMapping(VAppCloneSpecNetworkMappingPair[] networkMapping) {
        this.networkMapping = networkMapping;
    }

    public KeyValue[] getProperty() {
        if ((property) == null) {
            return (NULL_PROPERTY_ARRAY);
        }
        return property;
    }

    public void setProperty(KeyValue[] property) {
        this.property = property;
    }

    public VAppCloneSpecResourceMap[] getResourceMapping() {
        if ((resourceMapping) == null) {
            return (NULL_RESOURCE_MAPPING_ARRAY);
        }
        return resourceMapping;
    }

    public void setResourceMapping(VAppCloneSpecResourceMap[] resourceMapping) {
        this.resourceMapping = resourceMapping;
    }

    public String getProvisioning() {
        return provisioning;
    }

    public void setProvisioning(String provisioning) {
        this.provisioning = provisioning;
    }

}
