//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VirtualDiskOptionVFlashCacheConfigOption
    extends DynamicData
{

    public ChoiceOption cacheConsistencyType;
    public ChoiceOption cacheMode;
    public LongOption reservationInMB;
    public LongOption blockSizeInKB;

    public ChoiceOption getCacheConsistencyType() {
        return cacheConsistencyType;
    }

    public void setCacheConsistencyType(ChoiceOption cacheConsistencyType) {
        this.cacheConsistencyType = cacheConsistencyType;
    }

    public ChoiceOption getCacheMode() {
        return cacheMode;
    }

    public void setCacheMode(ChoiceOption cacheMode) {
        this.cacheMode = cacheMode;
    }

    public LongOption getReservationInMB() {
        return reservationInMB;
    }

    public void setReservationInMB(LongOption reservationInMB) {
        this.reservationInMB = reservationInMB;
    }

    public LongOption getBlockSizeInKB() {
        return blockSizeInKB;
    }

    public void setBlockSizeInKB(LongOption blockSizeInKB) {
        this.blockSizeInKB = blockSizeInKB;
    }

}
