//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VirtualMachineProfileDetails
    extends DynamicData
{

    private final static VirtualMachineProfileSpec[] NULL_PROFILE_ARRAY = new VirtualMachineProfileSpec[ 0 ] ;
    public VirtualMachineProfileSpec[] profile;
    private final static VirtualMachineProfileDetailsDiskProfileDetails[] NULL_DISK_PROFILE_DETAILS_ARRAY = new VirtualMachineProfileDetailsDiskProfileDetails[ 0 ] ;
    public VirtualMachineProfileDetailsDiskProfileDetails[] diskProfileDetails;

    public VirtualMachineProfileSpec[] getProfile() {
        if ((profile) == null) {
            return (NULL_PROFILE_ARRAY);
        }
        return profile;
    }

    public void setProfile(VirtualMachineProfileSpec[] profile) {
        this.profile = profile;
    }

    public VirtualMachineProfileDetailsDiskProfileDetails[] getDiskProfileDetails() {
        if ((diskProfileDetails) == null) {
            return (NULL_DISK_PROFILE_DETAILS_ARRAY);
        }
        return diskProfileDetails;
    }

    public void setDiskProfileDetails(VirtualMachineProfileDetailsDiskProfileDetails[] diskProfileDetails) {
        this.diskProfileDetails = diskProfileDetails;
    }

}
