//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VirtualMachineSriovInfo
    extends VirtualMachinePciPassthroughInfo
{

    public boolean virtualFunction;
    public String pnic;
    public VirtualMachineSriovDevicePoolInfo devicePool;

    public boolean getVirtualFunction() {
        return virtualFunction;
    }

    public void setVirtualFunction(boolean virtualFunction) {
        this.virtualFunction = virtualFunction;
    }

    public boolean isVirtualFunction() {
        return virtualFunction;
    }

    public String getPnic() {
        return pnic;
    }

    public void setPnic(String pnic) {
        this.pnic = pnic;
    }

    public VirtualMachineSriovDevicePoolInfo getDevicePool() {
        return devicePool;
    }

    public void setDevicePool(VirtualMachineSriovDevicePoolInfo devicePool) {
        this.devicePool = devicePool;
    }

}
