//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VirtualMachineForkConfigInfo
    extends DynamicData
{

    public Boolean parentEnabled;
    public String childForkGroupId;
    public String parentForkGroupId;
    public String childType;

    public Boolean getParentEnabled() {
        return parentEnabled;
    }

    public void setParentEnabled(Boolean parentEnabled) {
        this.parentEnabled = parentEnabled;
    }

    public Boolean isParentEnabled() {
        return parentEnabled;
    }

    public String getChildForkGroupId() {
        return childForkGroupId;
    }

    public void setChildForkGroupId(String childForkGroupId) {
        this.childForkGroupId = childForkGroupId;
    }

    public String getParentForkGroupId() {
        return parentForkGroupId;
    }

    public void setParentForkGroupId(String parentForkGroupId) {
        this.parentForkGroupId = parentForkGroupId;
    }

    public String getChildType() {
        return childType;
    }

    public void setChildType(String childType) {
        this.childType = childType;
    }

}
