//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VirtualMachineRelocateSpec
    extends DynamicData
{

    public ServiceLocator service;
    public ManagedObjectReference folder;
    public ManagedObjectReference datastore;
    public String diskMoveType;
    public ManagedObjectReference pool;
    public ManagedObjectReference host;
    private final static VirtualMachineRelocateSpecDiskLocator[] NULL_DISK_ARRAY = new VirtualMachineRelocateSpecDiskLocator[ 0 ] ;
    public VirtualMachineRelocateSpecDiskLocator[] disk;
    public VirtualMachineRelocateTransformation transform;
    private final static VirtualDeviceConfigSpec[] NULL_DEVICE_CHANGE_ARRAY = new VirtualDeviceConfigSpec[ 0 ] ;
    public VirtualDeviceConfigSpec[] deviceChange;
    private final static VirtualMachineProfileSpec[] NULL_PROFILE_ARRAY = new VirtualMachineProfileSpec[ 0 ] ;
    public VirtualMachineProfileSpec[] profile;

    public ServiceLocator getService() {
        return service;
    }

    public void setService(ServiceLocator service) {
        this.service = service;
    }

    public ManagedObjectReference getFolder() {
        return folder;
    }

    public void setFolder(ManagedObjectReference folder) {
        this.folder = folder;
    }

    public ManagedObjectReference getDatastore() {
        return datastore;
    }

    public void setDatastore(ManagedObjectReference datastore) {
        this.datastore = datastore;
    }

    public String getDiskMoveType() {
        return diskMoveType;
    }

    public void setDiskMoveType(String diskMoveType) {
        this.diskMoveType = diskMoveType;
    }

    public ManagedObjectReference getPool() {
        return pool;
    }

    public void setPool(ManagedObjectReference pool) {
        this.pool = pool;
    }

    public ManagedObjectReference getHost() {
        return host;
    }

    public void setHost(ManagedObjectReference host) {
        this.host = host;
    }

    public VirtualMachineRelocateSpecDiskLocator[] getDisk() {
        if ((disk) == null) {
            return (NULL_DISK_ARRAY);
        }
        return disk;
    }

    public void setDisk(VirtualMachineRelocateSpecDiskLocator[] disk) {
        this.disk = disk;
    }

    public VirtualMachineRelocateTransformation getTransform() {
        return transform;
    }

    public void setTransform(VirtualMachineRelocateTransformation transform) {
        this.transform = transform;
    }

    public VirtualDeviceConfigSpec[] getDeviceChange() {
        if ((deviceChange) == null) {
            return (NULL_DEVICE_CHANGE_ARRAY);
        }
        return deviceChange;
    }

    public void setDeviceChange(VirtualDeviceConfigSpec[] deviceChange) {
        this.deviceChange = deviceChange;
    }

    public VirtualMachineProfileSpec[] getProfile() {
        if ((profile) == null) {
            return (NULL_PROFILE_ARRAY);
        }
        return profile;
    }

    public void setProfile(VirtualMachineProfileSpec[] profile) {
        this.profile = profile;
    }

}
