//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VirtualMachineConfigInfoOverheadInfo
    extends DynamicData
{

    public Long initialMemoryReservation;
    public Long initialSwapReservation;

    public Long getInitialMemoryReservation() {
        return initialMemoryReservation;
    }

    public void setInitialMemoryReservation(Long initialMemoryReservation) {
        this.initialMemoryReservation = initialMemoryReservation;
    }

    public Long getInitialSwapReservation() {
        return initialSwapReservation;
    }

    public void setInitialSwapReservation(Long initialSwapReservation) {
        this.initialSwapReservation = initialSwapReservation;
    }

}
