//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VirtualUSB
    extends VirtualDevice
{

    public boolean connected;
    public Integer vendor;
    public Integer product;
    private final static String[] NULL_FAMILY_ARRAY = new String[ 0 ] ;
    public String[] family;
    private final static String[] NULL_SPEED_ARRAY = new String[ 0 ] ;
    public String[] speed;

    public boolean getConnected() {
        return connected;
    }

    public void setConnected(boolean connected) {
        this.connected = connected;
    }

    public boolean isConnected() {
        return connected;
    }

    public Integer getVendor() {
        return vendor;
    }

    public void setVendor(Integer vendor) {
        this.vendor = vendor;
    }

    public Integer getProduct() {
        return product;
    }

    public void setProduct(Integer product) {
        this.product = product;
    }

    public String[] getFamily() {
        if ((family) == null) {
            return (NULL_FAMILY_ARRAY);
        }
        return family;
    }

    public void setFamily(String[] family) {
        this.family = family;
    }

    public String[] getSpeed() {
        if ((speed) == null) {
            return (NULL_SPEED_ARRAY);
        }
        return speed;
    }

    public void setSpeed(String[] speed) {
        this.speed = speed;
    }

}
