//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VirtualDiskSeSparseBackingInfo
    extends VirtualDeviceFileBackingInfo
{

    public String diskMode;
    public Boolean writeThrough;
    public String uuid;
    public String contentId;
    public String changeId;
    public VirtualDiskSeSparseBackingInfo parent;
    public String deltaDiskFormat;
    public Boolean digestEnabled;
    public Integer grainSize;
    public CryptoKeyId keyId;

    public String getDiskMode() {
        return diskMode;
    }

    public void setDiskMode(String diskMode) {
        this.diskMode = diskMode;
    }

    public Boolean getWriteThrough() {
        return writeThrough;
    }

    public void setWriteThrough(Boolean writeThrough) {
        this.writeThrough = writeThrough;
    }

    public Boolean isWriteThrough() {
        return writeThrough;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getContentId() {
        return contentId;
    }

    public void setContentId(String contentId) {
        this.contentId = contentId;
    }

    public String getChangeId() {
        return changeId;
    }

    public void setChangeId(String changeId) {
        this.changeId = changeId;
    }

    public VirtualDiskSeSparseBackingInfo getParent() {
        return parent;
    }

    public void setParent(VirtualDiskSeSparseBackingInfo parent) {
        this.parent = parent;
    }

    public String getDeltaDiskFormat() {
        return deltaDiskFormat;
    }

    public void setDeltaDiskFormat(String deltaDiskFormat) {
        this.deltaDiskFormat = deltaDiskFormat;
    }

    public Boolean getDigestEnabled() {
        return digestEnabled;
    }

    public void setDigestEnabled(Boolean digestEnabled) {
        this.digestEnabled = digestEnabled;
    }

    public Boolean isDigestEnabled() {
        return digestEnabled;
    }

    public Integer getGrainSize() {
        return grainSize;
    }

    public void setGrainSize(Integer grainSize) {
        this.grainSize = grainSize;
    }

    public CryptoKeyId getKeyId() {
        return keyId;
    }

    public void setKeyId(CryptoKeyId keyId) {
        this.keyId = keyId;
    }

}
