//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VirtualMachineQuestionInfo
    extends DynamicData
{

    public String id;
    public String text;
    public ChoiceOption choice;
    private final static VirtualMachineMessage[] NULL_MESSAGE_ARRAY = new VirtualMachineMessage[ 0 ] ;
    public VirtualMachineMessage[] message;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public ChoiceOption getChoice() {
        return choice;
    }

    public void setChoice(ChoiceOption choice) {
        this.choice = choice;
    }

    public VirtualMachineMessage[] getMessage() {
        if ((message) == null) {
            return (NULL_MESSAGE_ARRAY);
        }
        return message;
    }

    public void setMessage(VirtualMachineMessage[] message) {
        this.message = message;
    }

}
