//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VmConfigFileQueryFilter
    extends DynamicData
{

    private final static int[] NULL_MATCH_CONFIG_VERSION_ARRAY = new int[ 0 ] ;
    public int[] matchConfigVersion;
    public Boolean encrypted;

    public int[] getMatchConfigVersion() {
        if ((matchConfigVersion) == null) {
            return (NULL_MATCH_CONFIG_VERSION_ARRAY);
        }
        return matchConfigVersion;
    }

    public void setMatchConfigVersion(int[] matchConfigVersion) {
        this.matchConfigVersion = matchConfigVersion;
    }

    public Boolean getEncrypted() {
        return encrypted;
    }

    public void setEncrypted(Boolean encrypted) {
        this.encrypted = encrypted;
    }

    public Boolean isEncrypted() {
        return encrypted;
    }

}
