//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VmConfigInfo
    extends DynamicData
{

    private final static VAppProductInfo[] NULL_PRODUCT_ARRAY = new VAppProductInfo[ 0 ] ;
    public VAppProductInfo[] product;
    private final static VAppPropertyInfo[] NULL_PROPERTY_ARRAY = new VAppPropertyInfo[ 0 ] ;
    public VAppPropertyInfo[] property;
    public VAppIPAssignmentInfo ipAssignment;
    private final static String[] NULL_EULA_ARRAY = new String[ 0 ] ;
    public String[] eula;
    private final static VAppOvfSectionInfo[] NULL_OVF_SECTION_ARRAY = new VAppOvfSectionInfo[ 0 ] ;
    public VAppOvfSectionInfo[] ovfSection;
    private final static String[] NULL_OVF_ENVIRONMENT_TRANSPORT_ARRAY = new String[ 0 ] ;
    public String[] ovfEnvironmentTransport;
    public boolean installBootRequired;
    public int installBootStopDelay;

    public VAppProductInfo[] getProduct() {
        if ((product) == null) {
            return (NULL_PRODUCT_ARRAY);
        }
        return product;
    }

    public void setProduct(VAppProductInfo[] product) {
        this.product = product;
    }

    public VAppPropertyInfo[] getProperty() {
        if ((property) == null) {
            return (NULL_PROPERTY_ARRAY);
        }
        return property;
    }

    public void setProperty(VAppPropertyInfo[] property) {
        this.property = property;
    }

    public VAppIPAssignmentInfo getIpAssignment() {
        return ipAssignment;
    }

    public void setIpAssignment(VAppIPAssignmentInfo ipAssignment) {
        this.ipAssignment = ipAssignment;
    }

    public String[] getEula() {
        if ((eula) == null) {
            return (NULL_EULA_ARRAY);
        }
        return eula;
    }

    public void setEula(String[] eula) {
        this.eula = eula;
    }

    public VAppOvfSectionInfo[] getOvfSection() {
        if ((ovfSection) == null) {
            return (NULL_OVF_SECTION_ARRAY);
        }
        return ovfSection;
    }

    public void setOvfSection(VAppOvfSectionInfo[] ovfSection) {
        this.ovfSection = ovfSection;
    }

    public String[] getOvfEnvironmentTransport() {
        if ((ovfEnvironmentTransport) == null) {
            return (NULL_OVF_ENVIRONMENT_TRANSPORT_ARRAY);
        }
        return ovfEnvironmentTransport;
    }

    public void setOvfEnvironmentTransport(String[] ovfEnvironmentTransport) {
        this.ovfEnvironmentTransport = ovfEnvironmentTransport;
    }

    public boolean getInstallBootRequired() {
        return installBootRequired;
    }

    public void setInstallBootRequired(boolean installBootRequired) {
        this.installBootRequired = installBootRequired;
    }

    public boolean isInstallBootRequired() {
        return installBootRequired;
    }

    public int getInstallBootStopDelay() {
        return installBootStopDelay;
    }

    public void setInstallBootStopDelay(int installBootStopDelay) {
        this.installBootStopDelay = installBootStopDelay;
    }

}
