//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VmDiskFileQueryFilter
    extends DynamicData
{

    private final static String[] NULL_DISK_TYPE_ARRAY = new String[ 0 ] ;
    public String[] diskType;
    private final static int[] NULL_MATCH_HARDWARE_VERSION_ARRAY = new int[ 0 ] ;
    public int[] matchHardwareVersion;
    private final static String[] NULL_CONTROLLER_TYPE_ARRAY = new String[ 0 ] ;
    public String[] controllerType;
    public Boolean thin;
    public Boolean encrypted;

    public String[] getDiskType() {
        if ((diskType) == null) {
            return (NULL_DISK_TYPE_ARRAY);
        }
        return diskType;
    }

    public void setDiskType(String[] diskType) {
        this.diskType = diskType;
    }

    public int[] getMatchHardwareVersion() {
        if ((matchHardwareVersion) == null) {
            return (NULL_MATCH_HARDWARE_VERSION_ARRAY);
        }
        return matchHardwareVersion;
    }

    public void setMatchHardwareVersion(int[] matchHardwareVersion) {
        this.matchHardwareVersion = matchHardwareVersion;
    }

    public String[] getControllerType() {
        if ((controllerType) == null) {
            return (NULL_CONTROLLER_TYPE_ARRAY);
        }
        return controllerType;
    }

    public void setControllerType(String[] controllerType) {
        this.controllerType = controllerType;
    }

    public Boolean getThin() {
        return thin;
    }

    public void setThin(Boolean thin) {
        this.thin = thin;
    }

    public Boolean isThin() {
        return thin;
    }

    public Boolean getEncrypted() {
        return encrypted;
    }

    public void setEncrypted(Boolean encrypted) {
        this.encrypted = encrypted;
    }

    public Boolean isEncrypted() {
        return encrypted;
    }

}
