//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VmfsUnmapBandwidthSpec
    extends DynamicData
{

    public String policy;
    public long fixedValue;
    public long dynamicMin;
    public long dynamicMax;

    public String getPolicy() {
        return policy;
    }

    public void setPolicy(String policy) {
        this.policy = policy;
    }

    public long getFixedValue() {
        return fixedValue;
    }

    public void setFixedValue(long fixedValue) {
        this.fixedValue = fixedValue;
    }

    public long getDynamicMin() {
        return dynamicMin;
    }

    public void setDynamicMin(long dynamicMin) {
        this.dynamicMin = dynamicMin;
    }

    public long getDynamicMax() {
        return dynamicMax;
    }

    public void setDynamicMax(long dynamicMax) {
        this.dynamicMax = dynamicMax;
    }

}
