//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VmfsDatastoreMultipleExtentOption
    extends VmfsDatastoreBaseOption
{

    private final static HostDiskPartitionBlockRange[] NULL_VMFS_EXTENT_ARRAY = new HostDiskPartitionBlockRange[ 0 ] ;
    public HostDiskPartitionBlockRange[] vmfsExtent;

    public HostDiskPartitionBlockRange[] getVmfsExtent() {
        if ((vmfsExtent) == null) {
            return (NULL_VMFS_EXTENT_ARRAY);
        }
        return vmfsExtent;
    }

    public void setVmfsExtent(HostDiskPartitionBlockRange[] vmfsExtent) {
        this.vmfsExtent = vmfsExtent;
    }

}
