//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VmfsDatastoreCreateSpec
    extends VmfsDatastoreSpec
{

    public HostDiskPartitionSpec partition;
    public HostVmfsSpec vmfs;
    private final static HostScsiDiskPartition[] NULL_EXTENT_ARRAY = new HostScsiDiskPartition[ 0 ] ;
    public HostScsiDiskPartition[] extent;

    public HostDiskPartitionSpec getPartition() {
        return partition;
    }

    public void setPartition(HostDiskPartitionSpec partition) {
        this.partition = partition;
    }

    public HostVmfsSpec getVmfs() {
        return vmfs;
    }

    public void setVmfs(HostVmfsSpec vmfs) {
        this.vmfs = vmfs;
    }

    public HostScsiDiskPartition[] getExtent() {
        if ((extent) == null) {
            return (NULL_EXTENT_ARRAY);
        }
        return extent;
    }

    public void setExtent(HostScsiDiskPartition[] extent) {
        this.extent = extent;
    }

}
