//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VMwareDVSPortSetting
    extends DVPortSetting
{

    public VmwareDistributedVirtualSwitchVlanSpec vlan;
    public IntPolicy qosTag;
    public VmwareUplinkPortTeamingPolicy uplinkTeamingPolicy;
    public DVSSecurityPolicy securityPolicy;
    public BoolPolicy ipfixEnabled;
    public BoolPolicy txUplink;
    public VMwareUplinkLacpPolicy lacpPolicy;
    public DVSMacManagementPolicy macManagementPolicy;

    public VmwareDistributedVirtualSwitchVlanSpec getVlan() {
        return vlan;
    }

    public void setVlan(VmwareDistributedVirtualSwitchVlanSpec vlan) {
        this.vlan = vlan;
    }

    public IntPolicy getQosTag() {
        return qosTag;
    }

    public void setQosTag(IntPolicy qosTag) {
        this.qosTag = qosTag;
    }

    public VmwareUplinkPortTeamingPolicy getUplinkTeamingPolicy() {
        return uplinkTeamingPolicy;
    }

    public void setUplinkTeamingPolicy(VmwareUplinkPortTeamingPolicy uplinkTeamingPolicy) {
        this.uplinkTeamingPolicy = uplinkTeamingPolicy;
    }

    public DVSSecurityPolicy getSecurityPolicy() {
        return securityPolicy;
    }

    public void setSecurityPolicy(DVSSecurityPolicy securityPolicy) {
        this.securityPolicy = securityPolicy;
    }

    public BoolPolicy getIpfixEnabled() {
        return ipfixEnabled;
    }

    public void setIpfixEnabled(BoolPolicy ipfixEnabled) {
        this.ipfixEnabled = ipfixEnabled;
    }

    public BoolPolicy getTxUplink() {
        return txUplink;
    }

    public void setTxUplink(BoolPolicy txUplink) {
        this.txUplink = txUplink;
    }

    public VMwareUplinkLacpPolicy getLacpPolicy() {
        return lacpPolicy;
    }

    public void setLacpPolicy(VMwareUplinkLacpPolicy lacpPolicy) {
        this.lacpPolicy = lacpPolicy;
    }

    public DVSMacManagementPolicy getMacManagementPolicy() {
        return macManagementPolicy;
    }

    public void setMacManagementPolicy(DVSMacManagementPolicy macManagementPolicy) {
        this.macManagementPolicy = macManagementPolicy;
    }

}
