//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
public class VmwareUplinkPortTeamingPolicy
    extends InheritablePolicy
{

    public StringPolicy policy;
    public BoolPolicy reversePolicy;
    public BoolPolicy notifySwitches;
    public BoolPolicy rollingOrder;
    public DVSFailureCriteria failureCriteria;
    public VMwareUplinkPortOrderPolicy uplinkPortOrder;

    public StringPolicy getPolicy() {
        return policy;
    }

    public void setPolicy(StringPolicy policy) {
        this.policy = policy;
    }

    public BoolPolicy getReversePolicy() {
        return reversePolicy;
    }

    public void setReversePolicy(BoolPolicy reversePolicy) {
        this.reversePolicy = reversePolicy;
    }

    public BoolPolicy getNotifySwitches() {
        return notifySwitches;
    }

    public void setNotifySwitches(BoolPolicy notifySwitches) {
        this.notifySwitches = notifySwitches;
    }

    public BoolPolicy getRollingOrder() {
        return rollingOrder;
    }

    public void setRollingOrder(BoolPolicy rollingOrder) {
        this.rollingOrder = rollingOrder;
    }

    public DVSFailureCriteria getFailureCriteria() {
        return failureCriteria;
    }

    public void setFailureCriteria(DVSFailureCriteria failureCriteria) {
        this.failureCriteria = failureCriteria;
    }

    public VMwareUplinkPortOrderPolicy getUplinkPortOrder() {
        return uplinkPortOrder;
    }

    public void setUplinkPortOrder(VMwareUplinkPortOrderPolicy uplinkPortOrder) {
        this.uplinkPortOrder = uplinkPortOrder;
    }

}
