//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VsanUpgradeSystemNetworkPartitionIssue
    extends VsanUpgradeSystemPreflightCheckIssue
{

    private final static VsanUpgradeSystemNetworkPartitionInfo[] NULL_PARTITIONS_ARRAY = new VsanUpgradeSystemNetworkPartitionInfo[ 0 ] ;
    public VsanUpgradeSystemNetworkPartitionInfo[] partitions;

    public VsanUpgradeSystemNetworkPartitionInfo[] getPartitions() {
        if ((partitions) == null) {
            return (NULL_PARTITIONS_ARRAY);
        }
        return partitions;
    }

    public void setPartitions(VsanUpgradeSystemNetworkPartitionInfo[] partitions) {
        this.partitions = partitions;
    }

}
