//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.vim25;



/**
 * 
 */
@SuppressWarnings("all")
public class VsanHostConfigInfoNetworkInfo
    extends DynamicData
{

    private final static VsanHostConfigInfoNetworkInfoPortConfig[] NULL_PORT_ARRAY = new VsanHostConfigInfoNetworkInfoPortConfig[ 0 ] ;
    public VsanHostConfigInfoNetworkInfoPortConfig[] port;

    public VsanHostConfigInfoNetworkInfoPortConfig[] getPort() {
        if ((port) == null) {
            return (NULL_PORT_ARRAY);
        }
        return port;
    }

    public void setPort(VsanHostConfigInfoNetworkInfoPortConfig[] port) {
        this.port = port;
    }

}
