//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.pbm;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPbmCompliancePolicyStatus {

    private final static com.vmware.pbm.PbmCompliancePolicyStatus[] NULL_PBM_COMPLIANCE_POLICY_STATUS_ARRAY = new com.vmware.pbm.PbmCompliancePolicyStatus[ 0 ] ;
    public com.vmware.pbm.PbmCompliancePolicyStatus[] PbmCompliancePolicyStatus;

    public com.vmware.pbm.PbmCompliancePolicyStatus[] getPbmCompliancePolicyStatus() {
        if ((PbmCompliancePolicyStatus) == null) {
            return (NULL_PBM_COMPLIANCE_POLICY_STATUS_ARRAY);
        }
        return PbmCompliancePolicyStatus;
    }

    public void setPbmCompliancePolicyStatus(com.vmware.pbm.PbmCompliancePolicyStatus[] PbmCompliancePolicyStatus) {
        this.PbmCompliancePolicyStatus = PbmCompliancePolicyStatus;
    }

}
