//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.pbm;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPbmPlacementResourceUtilization {

    private final static com.vmware.pbm.PbmPlacementResourceUtilization[] NULL_PBM_PLACEMENT_RESOURCE_UTILIZATION_ARRAY = new com.vmware.pbm.PbmPlacementResourceUtilization[ 0 ] ;
    public com.vmware.pbm.PbmPlacementResourceUtilization[] PbmPlacementResourceUtilization;

    public com.vmware.pbm.PbmPlacementResourceUtilization[] getPbmPlacementResourceUtilization() {
        if ((PbmPlacementResourceUtilization) == null) {
            return (NULL_PBM_PLACEMENT_RESOURCE_UTILIZATION_ARRAY);
        }
        return PbmPlacementResourceUtilization;
    }

    public void setPbmPlacementResourceUtilization(com.vmware.pbm.PbmPlacementResourceUtilization[] PbmPlacementResourceUtilization) {
        this.PbmPlacementResourceUtilization = PbmPlacementResourceUtilization;
    }

}
