//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.pbm;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPbmCapabilityPropertyInstance {

    private final static com.vmware.pbm.PbmCapabilityPropertyInstance[] NULL_PBM_CAPABILITY_PROPERTY_INSTANCE_ARRAY = new com.vmware.pbm.PbmCapabilityPropertyInstance[ 0 ] ;
    public com.vmware.pbm.PbmCapabilityPropertyInstance[] PbmCapabilityPropertyInstance;

    public com.vmware.pbm.PbmCapabilityPropertyInstance[] getPbmCapabilityPropertyInstance() {
        if ((PbmCapabilityPropertyInstance) == null) {
            return (NULL_PBM_CAPABILITY_PROPERTY_INSTANCE_ARRAY);
        }
        return PbmCapabilityPropertyInstance;
    }

    public void setPbmCapabilityPropertyInstance(com.vmware.pbm.PbmCapabilityPropertyInstance[] PbmCapabilityPropertyInstance) {
        this.PbmCapabilityPropertyInstance = PbmCapabilityPropertyInstance;
    }

}
