//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.pbm;



/**
 * 
 */
@SuppressWarnings("all")
public class ArrayOfPbmProfileId {

    private final static com.vmware.pbm.PbmProfileId[] NULL_PBM_PROFILE_ID_ARRAY = new com.vmware.pbm.PbmProfileId[ 0 ] ;
    public com.vmware.pbm.PbmProfileId[] PbmProfileId;

    public com.vmware.pbm.PbmProfileId[] getPbmProfileId() {
        if ((PbmProfileId) == null) {
            return (NULL_PBM_PROFILE_ID_ARRAY);
        }
        return PbmProfileId;
    }

    public void setPbmProfileId(com.vmware.pbm.PbmProfileId[] PbmProfileId) {
        this.PbmProfileId = PbmProfileId;
    }

}
