//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.pbm;

import com.vmware.vim25.DynamicData;


/**
 * 
 */
@SuppressWarnings("all")
public class PbmCapabilityMetadata
    extends DynamicData
{

    public PbmCapabilityMetadataUniqueId id;
    public PbmExtendedElementDescription summary;
    public Boolean mandatory;
    public Boolean hint;
    public String keyId;
    public Boolean allowMultipleConstraints;
    private final static PbmCapabilityPropertyMetadata[] NULL_PROPERTY_METADATA_ARRAY = new PbmCapabilityPropertyMetadata[ 0 ] ;
    public PbmCapabilityPropertyMetadata[] propertyMetadata;

    public PbmCapabilityMetadataUniqueId getId() {
        return id;
    }

    public void setId(PbmCapabilityMetadataUniqueId id) {
        this.id = id;
    }

    public PbmExtendedElementDescription getSummary() {
        return summary;
    }

    public void setSummary(PbmExtendedElementDescription summary) {
        this.summary = summary;
    }

    public Boolean getMandatory() {
        return mandatory;
    }

    public void setMandatory(Boolean mandatory) {
        this.mandatory = mandatory;
    }

    public Boolean isMandatory() {
        return mandatory;
    }

    public Boolean getHint() {
        return hint;
    }

    public void setHint(Boolean hint) {
        this.hint = hint;
    }

    public Boolean isHint() {
        return hint;
    }

    public String getKeyId() {
        return keyId;
    }

    public void setKeyId(String keyId) {
        this.keyId = keyId;
    }

    public Boolean getAllowMultipleConstraints() {
        return allowMultipleConstraints;
    }

    public void setAllowMultipleConstraints(Boolean allowMultipleConstraints) {
        this.allowMultipleConstraints = allowMultipleConstraints;
    }

    public Boolean isAllowMultipleConstraints() {
        return allowMultipleConstraints;
    }

    public PbmCapabilityPropertyMetadata[] getPropertyMetadata() {
        if ((propertyMetadata) == null) {
            return (NULL_PROPERTY_METADATA_ARRAY);
        }
        return propertyMetadata;
    }

    public void setPropertyMetadata(PbmCapabilityPropertyMetadata[] propertyMetadata) {
        this.propertyMetadata = propertyMetadata;
    }

}
