//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.12 at 09:16:35 AM EDT 
//


package com.vmware.pbm;



/**
 * 
 */
@SuppressWarnings("all")
public class PbmPersistenceBasedDataServiceInfo
    extends PbmLineOfServiceInfo
{

    private final static String[] NULL_COMPATIBLE_PERSISTENCE_SCHEMA_NAMESPACE_ARRAY = new String[ 0 ] ;
    public String[] compatiblePersistenceSchemaNamespace;

    public String[] getCompatiblePersistenceSchemaNamespace() {
        if ((compatiblePersistenceSchemaNamespace) == null) {
            return (NULL_COMPATIBLE_PERSISTENCE_SCHEMA_NAMESPACE_ARRAY);
        }
        return compatiblePersistenceSchemaNamespace;
    }

    public void setCompatiblePersistenceSchemaNamespace(String[] compatiblePersistenceSchemaNamespace) {
        this.compatiblePersistenceSchemaNamespace = compatiblePersistenceSchemaNamespace;
    }

}
